//! Bundled **offline** city/country index — the primary source for location
//! autocomplete.
//!
//! Two assets are compiled into the binary (no network at build time, no new
//! SQLite table, no search-engine dependency):
//!
//! * `geodata/cities.tsv.gz` — ~34k rows from GeoNames `cities15000`
//!   (population > 15 000 or a capital — the dump has grown well past the
//!   "~25k" GeoNames' own docs still quote), stripped to
//!   `name · asciiname · cc · lat · lon · population · alternates`.
//! * `geodata/countries.tsv` — ~250 rows from GeoNames `countryInfo.txt`
//!   (`cc · ISO3 · English country name · population`), so country-level
//!   queries resolve too and every city gets its `"City, Country"` label
//!   without a second lookup.
//!
//! Provenance, license (CC BY 4.0) and the refresh procedure live in
//! `geodata/README.md`; the assets are regenerated by
//! `scripts/build-geonames-index.mjs`.
//!
//! The index is built **once** on first use ([`LazyLock`]) and then only read:
//! decompress → parse → fold every search key through the SAME
//! [`fold`] the clustering layer uses, so `München`/`Muenchen`-class
//! equivalences can never drift between the two call sites. A query then costs
//! one `starts_with` scan over pre-folded `&str`s — no I/O, no allocation
//! beyond the (at most `limit`) suggestions actually returned.
//!
//! **Measured cost** — release build: ~60–78 ms for the one-time build
//! (decompress + fold ~34k rows), then ~7–11 ms per query. Debug build:
//! ~247 ms and ~11–15 ms. Retained memory ~10–12 MB. Every query sits behind
//! the picker's 300 ms debounce and runs on a Tauri command worker, so a
//! first-character bucket index (which would cut the scan ~30×) buys nothing a
//! user can perceive and is deliberately NOT built — it is the known lever if
//! this ever lands on a hot path.

use std::collections::HashMap;
use std::io::Read;
use std::sync::LazyLock;

use serde_json::{json, Value};

use crate::scraping::cluster::normalize::fold;

// TODO(arch): this module is real domain logic (a gazetteer + a ranking model)
// living under `commands/`, which is meant to be a thin IPC layer. If a second
// geo concern ever appears — reverse lookup, a radius/bounding-box filter, a
// second data source — promote it to a top-level `geo/` module and leave
// `commands::geocoding` as the IPC shim it is supposed to be. Not moved now:
// one consumer, one file, and the move would churn the whole diff for zero
// behavior change.

const CITIES_GZ: &[u8] = include_bytes!("../../../geodata/cities.tsv.gz");
const COUNTRIES_TSV: &str = include_str!("../../../geodata/countries.tsv");

/// SHA-256 of the two embedded assets, recorded when they were generated from
/// the upstream dumps (see `geodata/README.md` for the fetch date and source
/// URLs). Asserted by a test: regenerating the asset without updating this
/// provenance record — or a corrupted checkout — fails the build rather than
/// silently shipping data of unknown origin.
/// (Test-gated: the digests exist to be *asserted*; a release build has no
/// reader for them and would warn about dead constants.)
#[cfg(test)]
pub(super) const CITIES_SHA256: &str =
    "fc0b8a097f36afe3816afc53d948360e5d4c4b70bc9c7a902020401ffd4c5df6";
#[cfg(test)]
pub(super) const COUNTRIES_SHA256: &str =
    "a630d7efae6f267ff42c2abc4f02970f5381f0cbeef8b9275b6286d1a0c5488d";

/// Endonyms and colloquial country names GeoNames' English-only `countryInfo`
/// cannot match. Deliberately **tiny and curated**: every entry here is a name
/// a user of a de/en app plausibly types into a location field and that would
/// otherwise prefix-match an unrelated city (`schweiz` → Schweizer-Reneke, ZA).
/// Anything not listed is not guessed — it falls through to Photon, which knows
/// every language. Keys must already be in [`fold`]ed form (asserted by a test)
/// and are matched **exactly**, never as a prefix.
const COUNTRY_ALIASES: &[(&str, &str)] = &[
    ("deutschland", "DE"),
    ("oesterreich", "AT"), // fold("österreich")
    ("schweiz", "CH"),
    ("suisse", "CH"),
    ("svizzera", "CH"),
    ("frankreich", "FR"),
    ("uk", "GB"),     // not an ISO code, but what people type
    ("espana", "ES"), // fold("españa")
    ("nederland", "NL"),
    ("polska", "PL"),
];

/// Match quality, best first; **population decides within a tier** (for a
/// country, its own population — that is what lets a country and a city share
/// the prefix tier honestly).
///
/// The two rules that matter: a name the user spelled out in full wins over
/// anything that merely starts with those letters (`berlin` → Berlin, DE, not
/// Berlin-Köpenick), and a country the user spelled out in full — as a name, an
/// ISO code, or a listed endonym — wins over every city (`germany`/`de`/`deu`/
/// `deutschland` → Germany). Country *prefixes* deliberately do NOT outrank
/// cities: a blanket "countries first" turns `ber` into Bermuda-before-Berlin.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
enum Tier {
    /// The query IS a country name, ISO-2/ISO-3 code, or listed endonym.
    CountryExact,
    /// The query IS a city's own name or its ASCII form.
    CityExact,
    /// The query is a prefix of a country/city name, or exactly one of a city's
    /// alternate spellings (`wien` → Vienna). Alternate-exact sits here rather
    /// than above the prefixes because GeoNames' alias lists contain enough
    /// short junk (`Ber` is an alternate of Véroia, GR) that population must
    /// get a vote.
    Prefix,
    /// The query is a prefix of an alternate spelling only — the weakest hit.
    AlternatePrefix,
}

/// How a folded query lines up with one `\n`-separated blob of folded keys.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Match {
    /// Some key is exactly the query.
    Exact,
    /// Some key starts with the query, none equals it.
    Prefix,
}

/// What [`Index::search`] found.
pub(super) struct Hits {
    pub(super) suggestions: Vec<Value>,
    /// True when at least one record matched a key **exactly** (country
    /// name/code/alias, city name/asciiname, or an alternate spelling).
    ///
    /// This is the honest confidence signal [`super::suggest`] gates the online
    /// fallback on. Non-emptiness is NOT that signal: `schweiz` prefix-matches
    /// Schweizer-Reneke, ZA — five confident-looking rows that would otherwise
    /// veto Photon and let a caller persist `za` for "Switzerland".
    pub(super) exact: bool,
}

struct City {
    /// Display name, as GeoNames spells it (`Köln`, `Munich`).
    name: String,
    /// ISO-2, upper-cased.
    country_code: String,
    lat: f64,
    lon: f64,
    population: u64,
    /// Folded `name` + `asciiname`, `\n`-separated.
    primary_keys: String,
    /// Folded alternate spellings (`münchen`, `praha`, …), `\n`-separated.
    alternate_keys: String,
}

struct Country {
    name: String,
    /// ISO-2, upper-cased.
    country_code: String,
    population: u64,
    /// Folded English country name — prefix-matchable (`germ` → Germany).
    key: String,
    /// Folded ISO-2 + ISO-3 codes and endonym aliases, `\n`-separated. Matched
    /// **exact-only**: prefix-matching two-letter codes would make every
    /// single-character query resolve to a country.
    exact_keys: String,
}

/// Which record a ranked hit points at. Indices are always in range — they are
/// produced by iterating the very vectors they index.
#[derive(Clone, Copy)]
enum Hit {
    Country(usize),
    City(usize),
}

pub(super) struct Index {
    cities: Vec<City>,
    countries: Vec<Country>,
    /// ISO-2 → English country name, for the `"City, Country"` display label.
    country_names: HashMap<String, String>,
}

static INDEX: LazyLock<Index> = LazyLock::new(load);

/// `\n`-join the folded form of every non-empty key.
fn folded_keys<'a>(keys: impl IntoIterator<Item = &'a str>) -> String {
    let mut out = String::new();
    for key in keys {
        let folded = fold(key.trim());
        if folded.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&folded);
    }
    out
}

/// Best match between an already-folded `query` and a blob of folded keys.
fn match_keys(keys: &str, query: &str) -> Option<Match> {
    let mut prefix = false;
    for key in keys.split('\n') {
        if key == query {
            return Some(Match::Exact); // nothing in this blob can beat it
        }
        prefix |= key.starts_with(query);
    }
    prefix.then_some(Match::Prefix)
}

/// Exact-only variant of [`match_keys`] for country codes/aliases.
fn matches_exactly(keys: &str, query: &str) -> bool {
    keys.split('\n').any(|key| key == query)
}

/// An ISO-2/ISO-3 code must be exactly N **ASCII letters** — `len()` alone is a
/// byte count, so a 2-byte `"é"` or a `"1a"` would otherwise sail through and
/// end up in a suggestion's `countryCode`, which callers treat as a real code.
fn is_country_code(value: &str, len: usize) -> bool {
    value.len() == len && value.bytes().all(|b| b.is_ascii_alphabetic())
}

fn load() -> Index {
    parse(&decode_cities(CITIES_GZ), COUNTRIES_TSV)
}

/// Gunzip the bundled city asset. A corrupt/truncated blob must not panic the
/// app — it degrades to an empty city list (countries still work, and every
/// city query falls through to the Photon fallback), with one warning so the
/// cause is visible. Split out of [`load`] so that path is unit-testable.
fn decode_cities(gz: &[u8]) -> String {
    let mut decoded = String::new();
    if let Err(e) = flate2::read::GzDecoder::new(gz).read_to_string(&mut decoded) {
        tracing::warn!("geonames: bundled city index unreadable: {e}");
        // A partial read leaves whatever decoded before the error in the
        // buffer; drop it rather than index half a truncated row.
        decoded.clear();
    }
    decoded
}

/// Build the index from already-decompressed TSV text. Split out of [`load`] so
/// every degradation path (short row, non-numeric coordinates, bogus country
/// code, duplicate `cc`, alias for a country the asset lacks) is unit-testable
/// without hand-rolling a gzip stream. A malformed row is always skipped, never
/// fatal — a partially-readable asset still beats no autocomplete.
fn parse(cities_tsv: &str, countries_tsv: &str) -> Index {
    let mut country_names = HashMap::new();
    let mut countries: Vec<Country> = Vec::new();
    let mut by_code: HashMap<String, usize> = HashMap::new();
    for line in countries_tsv.lines() {
        // cc · ISO3 · English name · population
        let cols: Vec<&str> = line.split('\t').collect();
        let [cc, iso3, name, population] = cols[..] else {
            continue;
        };
        if !is_country_code(cc, 2) || name.is_empty() {
            continue;
        }
        let cc = cc.to_ascii_uppercase();
        // A duplicate `cc` keeps the FIRST row: re-pointing `by_code` at a later
        // one would strand the aliases on an entry nothing can reach.
        if by_code.contains_key(&cc) {
            continue;
        }
        country_names.insert(cc.clone(), name.to_string());
        by_code.insert(cc.clone(), countries.len());
        countries.push(Country {
            key: folded_keys([name]),
            // A malformed ISO3 is dropped rather than indexed as a bogus key.
            exact_keys: folded_keys(
                [cc.as_str()]
                    .into_iter()
                    .chain(is_country_code(iso3, 3).then_some(iso3)),
            ),
            name: name.to_string(),
            country_code: cc,
            population: population.parse().unwrap_or(0),
        });
    }
    for (alias, cc) in COUNTRY_ALIASES {
        // An alias for a country the asset does not carry is simply dropped —
        // never a panic, never a silent second entry.
        if let Some(country) = by_code.get(*cc).and_then(|i| countries.get_mut(*i)) {
            country.exact_keys.push('\n');
            country.exact_keys.push_str(alias);
        }
    }

    let mut cities = Vec::new();
    for line in cities_tsv.lines() {
        let cols: Vec<&str> = line.split('\t').collect();
        // name · asciiname · cc · lat · lon · population · alternates
        let [name, asciiname, cc, lat, lon, population, alternates] = cols[..] else {
            continue;
        };
        let (Ok(lat), Ok(lon)) = (lat.parse::<f64>(), lon.parse::<f64>()) else {
            continue;
        };
        if name.is_empty() || !is_country_code(cc, 2) {
            continue;
        }
        cities.push(City {
            primary_keys: folded_keys([name, asciiname]),
            alternate_keys: folded_keys(alternates.split('|')),
            name: name.to_string(),
            country_code: cc.to_ascii_uppercase(),
            lat,
            lon,
            population: population.parse().unwrap_or(0),
        });
    }

    Index {
        cities,
        countries,
        country_names,
    }
}

impl Index {
    /// `"City, Country"` — or the bare city name when the ISO-2 code isn't in
    /// `countryInfo` (mirrors the pre-existing "no country → no comma" rule).
    fn display(&self, hit: Hit) -> String {
        match hit {
            Hit::Country(i) => self.countries[i].name.clone(),
            Hit::City(i) => {
                let city = &self.cities[i];
                match self.country_names.get(&city.country_code) {
                    Some(country) => format!("{}, {}", city.name, country),
                    None => city.name.clone(),
                }
            }
        }
    }

    /// Primary name of a hit — the deterministic final sort tie-break.
    fn name(&self, hit: Hit) -> &str {
        match hit {
            Hit::Country(i) => &self.countries[i].name,
            Hit::City(i) => &self.cities[i].name,
        }
    }

    fn suggestion(&self, hit: Hit) -> Value {
        let display = self.display(hit);
        match hit {
            // Country-level picks carry no coordinates: `countryInfo` has none,
            // and downstream only uses lat/lon for a city-radius filter.
            Hit::Country(i) => json!({
                "display": display,
                "lat": Value::Null,
                "lon": Value::Null,
                "countryCode": self.countries[i].country_code,
            }),
            Hit::City(i) => json!({
                "display": display,
                "lat": self.cities[i].lat,
                "lon": self.cities[i].lon,
                "countryCode": self.cities[i].country_code,
            }),
        }
    }

    /// Ranked, deduped, `limit`-capped suggestions for an already-folded query.
    fn search(&self, folded_query: &str, limit: usize) -> Hits {
        // (tier, population, hit, matched-a-key-exactly)
        let mut hits: Vec<(Tier, u64, Hit, bool)> = Vec::new();

        for (i, country) in self.countries.iter().enumerate() {
            let tier = if matches_exactly(&country.exact_keys, folded_query) {
                Tier::CountryExact
            } else {
                match match_keys(&country.key, folded_query) {
                    Some(Match::Exact) => Tier::CountryExact,
                    Some(Match::Prefix) => Tier::Prefix,
                    None => continue,
                }
            };
            let exact = tier == Tier::CountryExact;
            hits.push((tier, country.population, Hit::Country(i), exact));
        }

        for (i, city) in self.cities.iter().enumerate() {
            let primary = match_keys(&city.primary_keys, folded_query);
            let alternate = match_keys(&city.alternate_keys, folded_query);
            let tier = match (primary, alternate) {
                (Some(Match::Exact), _) => Tier::CityExact,
                (Some(Match::Prefix), _) | (None, Some(Match::Exact)) => Tier::Prefix,
                (None, Some(Match::Prefix)) => Tier::AlternatePrefix,
                (None, None) => continue,
            };
            // An exact ALTERNATE ranks in the prefix tier (see `Tier`) but is
            // still an exact user-typed name, so it counts as confidence.
            let exact = primary == Some(Match::Exact) || alternate == Some(Match::Exact);
            hits.push((tier, city.population, Hit::City(i), exact));
        }

        hits.sort_by(|a, b| {
            a.0.cmp(&b.0)
                .then(b.1.cmp(&a.1))
                .then_with(|| self.name(a.2).cmp(self.name(b.2)))
        });
        // Lazy: `dedupe_by_display_with` stops at `limit`, so only the handful
        // of suggestions actually returned are ever materialized as JSON.
        let kept = super::dedupe_by_display_with(
            hits.into_iter()
                .map(|(_, _, hit, exact)| (self.suggestion(hit), exact)),
            limit,
        );
        // Confidence is derived ONLY from the records the caller can actually
        // see. An exact hit that ranked below the cap (or lost the dedupe) is
        // invisible, so letting it set this flag would veto the Photon fallback
        // on the strength of a row nobody was shown.
        let exact = kept.iter().any(|(_, exact)| *exact);
        Hits {
            suggestions: kept.into_iter().map(|(value, _)| value).collect(),
            exact,
        }
    }
}

/// Offline suggestions for `query`, with the match-quality signal
/// [`super::suggest`] gates the Photon fallback on.
pub(super) fn search(query: &str, limit: usize) -> Hits {
    let folded = fold(query.trim());
    if folded.is_empty() {
        return Hits {
            suggestions: vec![],
            exact: false,
        };
    }
    INDEX.search(&folded, limit)
}

/// Build the index now instead of on the first user keystroke.
///
/// The build is 60–250 ms of pure CPU. Left lazy it lands on whichever Tauri
/// command worker touches it first — and on the backfill path that worker is
/// inside `derive_country_code`'s `tokio::time::timeout`, which cannot
/// interrupt synchronous work, so the 2 s cap would silently not apply. Warmed
/// from `lib.rs`'s setup on a blocking thread, every later `search` is a pure
/// read of an already-initialized [`LazyLock`].
pub(super) fn warm() {
    LazyLock::force(&INDEX);
}

/// `(cities, countries)` row counts — lets the tests assert the real bundled
/// asset actually parsed instead of silently searching an empty index.
#[cfg(test)]
pub(super) fn row_counts() -> (usize, usize) {
    (INDEX.cities.len(), INDEX.countries.len())
}

/// The curated alias table, for the fold-stability regression test.
#[cfg(test)]
pub(super) fn aliases() -> &'static [(&'static str, &'static str)] {
    COUNTRY_ALIASES
}

/// The raw embedded assets, so a test can pin their provenance digests.
#[cfg(test)]
pub(super) fn embedded_assets() -> (&'static [u8], &'static str) {
    (CITIES_GZ, COUNTRIES_TSV)
}

/// [`parse`] with caller-supplied TSV text — the seam the degradation tests use.
#[cfg(test)]
pub(super) fn parse_for_test(cities_tsv: &str, countries_tsv: &str) -> Index {
    parse(cities_tsv, countries_tsv)
}

/// [`decode_cities`] for the corrupt-asset test.
#[cfg(test)]
pub(super) fn decode_cities_for_test(gz: &[u8]) -> String {
    decode_cities(gz)
}

#[cfg(test)]
impl Index {
    pub(super) fn counts(&self) -> (usize, usize) {
        (self.cities.len(), self.countries.len())
    }

    /// Suggestions for a RAW (unfolded) query against this index only — lets a
    /// degradation test query a hand-built index instead of the bundled one.
    pub(super) fn lookup(&self, query: &str, limit: usize) -> Hits {
        self.search(&fold(query.trim()), limit)
    }
}
