//! Bundled **offline** city/country index — the primary source for location
//! autocomplete.
//!
//! Two assets are compiled into the binary (no network at build time, no new
//! SQLite table, no search-engine dependency):
//!
//! * `geodata/cities.tsv.gz` — ~34k rows from GeoNames `cities15000`
//!   (population > 15 000 or a capital), stripped to
//!   `name · asciiname · cc · lat · lon · population · alternates`.
//! * `geodata/countries.tsv` — ~250 rows from GeoNames `countryInfo.txt`
//!   (`cc · ISO3 · English country name · population`), so country-level
//!   queries resolve too and every city gets its `"City, Country"` label
//!   without a second lookup.
//!
//! Provenance, license (CC BY 4.0) and the refresh procedure live in
//! `geodata/README.md`; the assets are regenerated by
//! `scripts/build-geonames-index.mjs`.
//!
//! The index is built **once** on first use ([`LazyLock`]) and then only read:
//! decompress → parse → fold every search key through the SAME
//! [`fold`] the clustering layer uses, so `München`/`Muenchen`-class
//! equivalences can never drift between the two call sites. A query then costs
//! one `starts_with` scan over pre-folded `&str`s — no I/O, no allocation
//! beyond the (at most `limit`) suggestions actually returned.
//!
//! **Measured cost** — release build: ~60–78 ms for the one-time build
//! (decompress + fold ~34k rows), then ~7–11 ms per query. Debug build:
//! ~247 ms and ~11–15 ms. Retained memory ~10–12 MB. Every query sits behind
//! the picker's 300 ms debounce and runs on a Tauri command worker, so a
//! first-character bucket index (which would cut the scan ~30×) buys nothing a
//! user can perceive and is deliberately NOT built — it is the known lever if
//! this ever lands on a hot path.

use std::collections::HashMap;
use std::io::Read;
use std::sync::LazyLock;

use serde_json::{json, Value};

use crate::scraping::cluster::normalize::fold;

const CITIES_GZ: &[u8] = include_bytes!("../../../geodata/cities.tsv.gz");
const COUNTRIES_TSV: &str = include_str!("../../../geodata/countries.tsv");

/// Endonyms and colloquial country names GeoNames' English-only `countryInfo`
/// cannot match. Deliberately **tiny and curated**: every entry here is a name
/// a user of a de/en app plausibly types into a location field and that would
/// otherwise prefix-match an unrelated city (`schweiz` → Schweizer-Reneke, ZA).
/// Anything not listed is not guessed — it falls through to Photon, which knows
/// every language. Keys must already be in [`fold`]ed form (asserted by a test)
/// and are matched **exactly**, never as a prefix.
const COUNTRY_ALIASES: &[(&str, &str)] = &[
    ("deutschland", "DE"),
    ("oesterreich", "AT"), // fold("österreich")
    ("schweiz", "CH"),
    ("suisse", "CH"),
    ("svizzera", "CH"),
    ("frankreich", "FR"),
    ("uk", "GB"),     // not an ISO code, but what people type
    ("espana", "ES"), // fold("españa")
    ("nederland", "NL"),
    ("polska", "PL"),
];

/// Match quality, best first; **population decides within a tier** (for a
/// country, its own population — that is what lets a country and a city share
/// the prefix tier honestly).
///
/// The two rules that matter: a name the user spelled out in full wins over
/// anything that merely starts with those letters (`berlin` → Berlin, DE, not
/// Berlin-Köpenick), and a country the user spelled out in full — as a name, an
/// ISO code, or a listed endonym — wins over every city (`germany`/`de`/`deu`/
/// `deutschland` → Germany). Country *prefixes* deliberately do NOT outrank
/// cities: a blanket "countries first" turns `ber` into Bermuda-before-Berlin.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
enum Tier {
    /// The query IS a country name, ISO-2/ISO-3 code, or listed endonym.
    CountryExact,
    /// The query IS a city's own name or its ASCII form.
    CityExact,
    /// The query is a prefix of a country/city name, or exactly one of a city's
    /// alternate spellings (`wien` → Vienna). Alternate-exact sits here rather
    /// than above the prefixes because GeoNames' alias lists contain enough
    /// short junk (`Ber` is an alternate of Véroia, GR) that population must
    /// get a vote.
    Prefix,
    /// The query is a prefix of an alternate spelling only — the weakest hit.
    AlternatePrefix,
}

/// How a folded query lines up with one `\n`-separated blob of folded keys.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Match {
    /// Some key is exactly the query.
    Exact,
    /// Some key starts with the query, none equals it.
    Prefix,
}

/// What [`Index::search`] found.
pub(super) struct Hits {
    pub(super) suggestions: Vec<Value>,
    /// True when at least one record matched a key **exactly** (country
    /// name/code/alias, city name/asciiname, or an alternate spelling).
    ///
    /// This is the honest confidence signal [`super::suggest`] gates the online
    /// fallback on. Non-emptiness is NOT that signal: `schweiz` prefix-matches
    /// Schweizer-Reneke, ZA — five confident-looking rows that would otherwise
    /// veto Photon and let a caller persist `za` for "Switzerland".
    pub(super) exact: bool,
}

struct City {
    /// Display name, as GeoNames spells it (`Köln`, `Munich`).
    name: String,
    /// ISO-2, upper-cased.
    country_code: String,
    lat: f64,
    lon: f64,
    population: u64,
    /// Folded `name` + `asciiname`, `\n`-separated.
    primary_keys: String,
    /// Folded alternate spellings (`münchen`, `praha`, …), `\n`-separated.
    alternate_keys: String,
}

struct Country {
    name: String,
    /// ISO-2, upper-cased.
    country_code: String,
    population: u64,
    /// Folded English country name — prefix-matchable (`germ` → Germany).
    key: String,
    /// Folded ISO-2 + ISO-3 codes and endonym aliases, `\n`-separated. Matched
    /// **exact-only**: prefix-matching two-letter codes would make every
    /// single-character query resolve to a country.
    exact_keys: String,
}

/// Which record a ranked hit points at. Indices are always in range — they are
/// produced by iterating the very vectors they index.
#[derive(Clone, Copy)]
enum Hit {
    Country(usize),
    City(usize),
}

pub(super) struct Index {
    cities: Vec<City>,
    countries: Vec<Country>,
    /// ISO-2 → English country name, for the `"City, Country"` display label.
    country_names: HashMap<String, String>,
}

static INDEX: LazyLock<Index> = LazyLock::new(load);

/// `\n`-join the folded form of every non-empty key.
fn folded_keys<'a>(keys: impl IntoIterator<Item = &'a str>) -> String {
    let mut out = String::new();
    for key in keys {
        let folded = fold(key.trim());
        if folded.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push('\n');
        }
        out.push_str(&folded);
    }
    out
}

/// Best match between an already-folded `query` and a blob of folded keys.
fn match_keys(keys: &str, query: &str) -> Option<Match> {
    let mut prefix = false;
    for key in keys.split('\n') {
        if key == query {
            return Some(Match::Exact); // nothing in this blob can beat it
        }
        prefix |= key.starts_with(query);
    }
    prefix.then_some(Match::Prefix)
}

/// Exact-only variant of [`match_keys`] for country codes/aliases.
fn matches_exactly(keys: &str, query: &str) -> bool {
    keys.split('\n').any(|key| key == query)
}

fn load() -> Index {
    let mut decoded = String::new();
    // A corrupt asset must not panic the app: an empty index just means every
    // query falls through to the Photon fallback.
    if let Err(e) = flate2::read::GzDecoder::new(CITIES_GZ).read_to_string(&mut decoded) {
        tracing::warn!("geonames: bundled city index unreadable: {e}");
    }

    let mut country_names = HashMap::new();
    let mut countries = Vec::new();
    let mut by_code: HashMap<String, usize> = HashMap::new();
    for line in COUNTRIES_TSV.lines() {
        // cc · ISO3 · English name · population
        let cols: Vec<&str> = line.split('\t').collect();
        let [cc, iso3, name, population] = cols[..] else {
            continue;
        };
        if cc.len() != 2 || name.is_empty() {
            continue;
        }
        let cc = cc.to_ascii_uppercase();
        country_names.insert(cc.clone(), name.to_string());
        by_code.insert(cc.clone(), countries.len());
        countries.push(Country {
            key: folded_keys([name]),
            exact_keys: folded_keys([cc.as_str(), iso3]),
            name: name.to_string(),
            country_code: cc,
            population: population.parse().unwrap_or(0),
        });
    }
    for (alias, cc) in COUNTRY_ALIASES {
        // An alias for a country the asset does not carry is simply dropped —
        // never a panic, never a silent second entry.
        if let Some(country) = by_code.get(*cc).and_then(|i| countries.get_mut(*i)) {
            country.exact_keys.push('\n');
            country.exact_keys.push_str(alias);
        }
    }

    let mut cities = Vec::new();
    for line in decoded.lines() {
        let cols: Vec<&str> = line.split('\t').collect();
        // name · asciiname · cc · lat · lon · population · alternates
        let [name, asciiname, cc, lat, lon, population, alternates] = cols[..] else {
            continue;
        };
        let (Ok(lat), Ok(lon)) = (lat.parse::<f64>(), lon.parse::<f64>()) else {
            continue;
        };
        if name.is_empty() || cc.len() != 2 {
            continue;
        }
        cities.push(City {
            primary_keys: folded_keys([name, asciiname]),
            alternate_keys: folded_keys(alternates.split('|')),
            name: name.to_string(),
            country_code: cc.to_ascii_uppercase(),
            lat,
            lon,
            population: population.parse().unwrap_or(0),
        });
    }

    Index {
        cities,
        countries,
        country_names,
    }
}

impl Index {
    /// `"City, Country"` — or the bare city name when the ISO-2 code isn't in
    /// `countryInfo` (mirrors the pre-existing "no country → no comma" rule).
    fn display(&self, hit: Hit) -> String {
        match hit {
            Hit::Country(i) => self.countries[i].name.clone(),
            Hit::City(i) => {
                let city = &self.cities[i];
                match self.country_names.get(&city.country_code) {
                    Some(country) => format!("{}, {}", city.name, country),
                    None => city.name.clone(),
                }
            }
        }
    }

    /// Primary name of a hit — the deterministic final sort tie-break.
    fn name(&self, hit: Hit) -> &str {
        match hit {
            Hit::Country(i) => &self.countries[i].name,
            Hit::City(i) => &self.cities[i].name,
        }
    }

    fn suggestion(&self, hit: Hit) -> Value {
        let display = self.display(hit);
        match hit {
            // Country-level picks carry no coordinates: `countryInfo` has none,
            // and downstream only uses lat/lon for a city-radius filter.
            Hit::Country(i) => json!({
                "display": display,
                "lat": Value::Null,
                "lon": Value::Null,
                "countryCode": self.countries[i].country_code,
            }),
            Hit::City(i) => json!({
                "display": display,
                "lat": self.cities[i].lat,
                "lon": self.cities[i].lon,
                "countryCode": self.cities[i].country_code,
            }),
        }
    }

    /// Ranked, deduped, `limit`-capped suggestions for an already-folded query.
    fn search(&self, folded_query: &str, limit: usize) -> Hits {
        let mut hits: Vec<(Tier, u64, Hit)> = Vec::new();
        let mut exact = false;

        for (i, country) in self.countries.iter().enumerate() {
            let tier = if matches_exactly(&country.exact_keys, folded_query) {
                Tier::CountryExact
            } else {
                match match_keys(&country.key, folded_query) {
                    Some(Match::Exact) => Tier::CountryExact,
                    Some(Match::Prefix) => Tier::Prefix,
                    None => continue,
                }
            };
            exact |= tier == Tier::CountryExact;
            hits.push((tier, country.population, Hit::Country(i)));
        }

        for (i, city) in self.cities.iter().enumerate() {
            let primary = match_keys(&city.primary_keys, folded_query);
            let alternate = match_keys(&city.alternate_keys, folded_query);
            let tier = match (primary, alternate) {
                (Some(Match::Exact), _) => Tier::CityExact,
                (Some(Match::Prefix), _) | (None, Some(Match::Exact)) => Tier::Prefix,
                (None, Some(Match::Prefix)) => Tier::AlternatePrefix,
                (None, None) => continue,
            };
            // An exact ALTERNATE ranks in the prefix tier (see `Tier`) but is
            // still an exact user-typed name, so it counts as confidence.
            exact |= primary == Some(Match::Exact) || alternate == Some(Match::Exact);
            hits.push((tier, city.population, Hit::City(i)));
        }

        hits.sort_by(|a, b| {
            a.0.cmp(&b.0)
                .then(b.1.cmp(&a.1))
                .then_with(|| self.name(a.2).cmp(self.name(b.2)))
        });
        // Lazy: `dedupe_by_display` stops at `limit`, so only the handful of
        // suggestions actually returned are ever materialized as JSON.
        let suggestions = super::dedupe_by_display(
            hits.into_iter().map(|(_, _, hit)| self.suggestion(hit)),
            limit,
        );
        Hits { suggestions, exact }
    }
}

/// Offline suggestions for `query`, with the match-quality signal
/// [`super::suggest`] gates the Photon fallback on.
pub(super) fn search(query: &str, limit: usize) -> Hits {
    let folded = fold(query.trim());
    if folded.is_empty() {
        return Hits {
            suggestions: vec![],
            exact: false,
        };
    }
    INDEX.search(&folded, limit)
}

/// `(cities, countries)` row counts — lets the tests assert the real bundled
/// asset actually parsed instead of silently searching an empty index.
#[cfg(test)]
pub(super) fn row_counts() -> (usize, usize) {
    (INDEX.cities.len(), INDEX.countries.len())
}

/// The curated alias table, for the fold-stability regression test.
#[cfg(test)]
pub(super) fn aliases() -> &'static [(&'static str, &'static str)] {
    COUNTRY_ALIASES
}
