// @generated by pnpm gen:prompts — DO NOT EDIT BY HAND.
//
//! Pure prompt BLOCKS shared with the TypeScript prompt builders.
//!
//! Source of truth: `packages/prompts` — `generate/emphasis`
//! (`FACTUAL_GROUNDING_RULES`), `generate/resume` (`ATS_PRECEDENCE`),
//! `generate/natural-voice` (`HUMANIZE_LEXICAL`), and `locale`
//! (`resumeConventions`). Generated by CALLING those exports, so a Rust stage
//! prompt and the renderer-driven prompt for the same job state the identical
//! rule instead of two paraphrases that drift.
//!
//! Run `pnpm gen:prompts` to regenerate after editing them; `pnpm
//! gen:prompts:check` fails the build when this file is stale.
#![allow(dead_code)]

/// The résumé is the ONLY source of claims about the candidate; the job ad
/// is a target, never evidence. Shared verbatim with the cover-letter,
/// application-email, and application-questions prompts.
pub const FACTUAL_GROUNDING_RULES: &str =
    "Every factual claim about the candidate MUST be traceable to a line in <candidate_resume>. Never claim skills or experience from <job_ad> alone.";

/// ATS keyword match outranks the anti-AI-tell word bans: an exact job-ad
/// term the résumé truthfully supports is kept even when it is on the
/// discouraged list. The bans govern only words the model introduces itself.
pub const ATS_PRECEDENCE: &str =
    "ATS PRECEDENCE: If a word the anti-AI-tell rules discourage is an EXACT term from the <job_ad> and is truthfully grounded in the candidate's résumé, keep it (ATS keyword match wins). The anti-AI-tell bans govern only words the model introduces on its own.";

/// The POSITIVE résumé-tier voice block — specificity and bullet variety —
/// composed ALONGSIDE the anti-AI-tell bans, never instead of them. Résumé
/// tier stays ATS-safe (no contractions, no fragments).
pub const HUMANIZE_LEXICAL: &str =
    "SPECIFICITY AND BULLET VARIETY (adds to the bans above, never replaces them; resume tier stays ATS safe, no contractions or fragments):\n- SPECIFICITY: prefer the real number, tool, or project name the resume already gives over a generic claim. \"Cut checkout latency from 480ms to 90ms with Redis caching\" beats \"improved performance using caching\".\n- BULLET VARIETY: every bullet still opens with a strong past-tense action verb, but vary the verb and the sentence construction after it within a role so bullets are not identical Verb, What, Tech, metric templates. Rows of identically shaped bullets are the single biggest resume AI tell.\n- This adds variety and specificity only. Every number, tool, and project still has to already be in the resume, exactly as the rules above require.";

/// Localized standard résumé section headers + a market-conventional date
/// range example.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResumeConventions {
    pub summary: &'static str,
    pub experience: &'static str,
    pub education: &'static str,
    pub skills: &'static str,
    pub date_example: &'static str,
}

/// Résumé conventions for `lang`, falling back to English for any locale the
/// prompt side has no curated entry for — the same normalization
/// (first two characters, lowercased) and the same fallback as the TS
/// `resumeConventions`.
pub fn resume_conventions(lang: &str) -> ResumeConventions {
    let key: String = lang.chars().take(2).flat_map(char::to_lowercase).collect();
    match key.as_str() {
        "de" => ResumeConventions {
            summary: "Profil",
            experience: "Berufserfahrung",
            education: "Ausbildung",
            skills: "Kenntnisse",
            date_example: "01/2021 – 03/2023",
        },
        "es" => ResumeConventions {
            summary: "Perfil",
            experience: "Experiencia profesional",
            education: "Formación",
            skills: "Habilidades",
            date_example: "enero 2021 – marzo 2023",
        },
        "fr" => ResumeConventions {
            summary: "Profil",
            experience: "Expérience professionnelle",
            education: "Formation",
            skills: "Compétences",
            date_example: "janvier 2021 – mars 2023",
        },
        "it" => ResumeConventions {
            summary: "Profilo",
            experience: "Esperienza professionale",
            education: "Formazione",
            skills: "Competenze",
            date_example: "gennaio 2021 – marzo 2023",
        },
        "nl" => ResumeConventions {
            summary: "Profiel",
            experience: "Werkervaring",
            education: "Opleiding",
            skills: "Vaardigheden",
            date_example: "01/2021 – 03/2023",
        },
        "pt" => ResumeConventions {
            summary: "Perfil",
            experience: "Experiência profissional",
            education: "Formação",
            skills: "Competências",
            date_example: "janeiro 2021 – março 2023",
        },
        // "en" and every uncurated locale.
        _ => ResumeConventions {
            summary: "Professional Summary",
            experience: "Work Experience",
            education: "Education",
            skills: "Skills",
            date_example: "January 2021 – March 2023",
        },
    }
}
