// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `applications_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "applications_accept_status_event",
        description: "Accept the SPECIFIC email-derived, unconfirmed status-event row `eventId` names — sets its `StatusEvent.confirmed` flag to `true`; the status itself is untouched.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
            CatalogueArg { name: "eventId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_delete",
        description: "Delete the Application and its status history — always irreversible; `keepDocuments: false` ALSO deletes every résumé/cover-letter generation produced for it, while `keepDocuments: true` instead detaches those generations, which survive as orphaned documents outside this Application.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
            CatalogueArg { name: "keepDocuments", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_get",
        description: "",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "applications_reject_status_event",
        description: "Reject the SPECIFIC email-derived, unconfirmed status-event row `eventId` names — reverts the status by compare-and-set (never clobbers a status that moved on, whether by the user's own hand or a later email, in the meantime) and appends a reversal event.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
            CatalogueArg { name: "eventId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_save_from_posting",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["jobUrl", "board", "company", "title", "candidate", "jobDescription", "salaryMin", "salaryMax", "salaryCurrency"]) },
        ],
    },
    CatalogueEntry {
        command: "applications_set_status",
        description: "Transition the status, optionally recording a free-text `note` — persisted on the appended `status_events` row and returned as `StatusEvent.note` by `get()` (the interaction log).",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
            CatalogueArg { name: "status", required: true, fields: None },
            CatalogueArg { name: "note", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_track",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["jobUrl", "board", "company", "title", "candidate", "jobDescription", "salaryMin", "salaryMax", "salaryCurrency"]) },
        ],
    },
    CatalogueEntry {
        command: "applications_update",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["id", "notes", "nextActionAt", "comp", "contactName", "contactEmail", "jobDescription", "jobSummary", "recipientName", "recipientEmail"]) },
        ],
    },
];
