// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `autopilot_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "autopilot_best_matches",
        description: "The current top-scoring matches across every non-archived autopilot, recomputed at query time (nothing about this list is persisted).",
        args: &[],
    },
    CatalogueEntry {
        command: "autopilot_create",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["name", "target", "filter", "schedule", "scheduleHour", "scheduleMinute", "resumeText", "coverLetter", "assistant", "assistantProvider", "assistantModel", "assistantBaseUrl"]) },
        ],
    },
    CatalogueEntry {
        command: "autopilot_get",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "autopilot_pause",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_remove",
        description: "Permanently delete this autopilot and stop its scheduled runs — the found-jobs history it built goes with it.",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_resume",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_run",
        description: "Run an autopilot now. The backend command *resolves* (does not reject) with an `{ error }` payload on a scrape failure or unknown id, so callers MUST inspect `error` — a resolved value is not proof of success.",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_take_pending_focus",
        description: "Atomically take + clear the autopilot-focus intent buffered by the shell.",
        args: &[],
    },
    CatalogueEntry {
        command: "autopilot_update",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
];
