// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `boards_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "boards_catalog",
        description: "Full scraper catalog (id, label, mode, auth tier, listed) from the registry — `SCRAPERS` in `apps/desktop/src-tauri/src/scraping/boards/mod.rs`, whose per-scraper `Scraper` impl owns the auth tier and the listed flag.",
        args: &[],
    },
    CatalogueEntry {
        command: "boards_get_status",
        description: "Get current connection status for a board.",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "boards_health",
        description: "Live per-board reliability across runs (Track B1).",
        args: &[],
    },
    CatalogueEntry {
        command: "boards_import_cookies",
        description: "Try to import session cookies from the user's installed Chromium browsers (Chrome, Edge, Brave), so the user can skip the in-app re-login.",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "boards_login_with_browser",
        description: "Connect to a board by launching a browser for manual login.",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "boards_logout",
        description: "Disconnect a board (closes context only; does not delete profile).",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
];
