// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `cli_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::CatalogueEntry;

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "cli_agents_redetect",
        description: "Clear the detection cache and re-probe (call after an install).",
        args: &[],
    },
    CatalogueEntry {
        command: "cli_agents_status",
        description: "Cached install status for every CLI agent (+ npm availability).",
        args: &[],
    },
];
