// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `contact_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "contact_profile_get",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "contact_profile_header_line",
        description: "The stored profile's header contact line as markdown, localized for `lang` — built by the single shared `ContactProfile::header_markdown` (Rust), never re-implemented here, so the ordering rules can't drift between the two languages.",
        args: &[
            CatalogueArg { name: "lang", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "contact_profile_set",
        description: "Rejects on failure (unmanaged store, invalid payload, storage error) — there is no in-band `{ error }` shape to inspect.",
        args: &[
            CatalogueArg { name: "profile", required: true, fields: Some(&["fullName", "email", "phone", "location", "linkedin", "github", "website", "extraLinks", "photo"]) },
        ],
    },
];
