// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `credentials_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::CatalogueEntry;

pub(super) const ENTRIES: &[CatalogueEntry] = &[CatalogueEntry {
    command: "credentials_available",
    description: "Whether the OS supports encrypted secret storage.",
    args: &[],
}];
