// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `data_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::CatalogueEntry;

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "data_export",
        description: "Export all user data to a user-chosen JSON file.",
        args: &[],
    },
    CatalogueEntry {
        command: "data_import",
        description: "Restore all user data from a user-chosen backup file (replace semantics).",
        args: &[],
    },
];
