// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `dedup_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "dedup_mark_not_duplicate",
        description: "Record a \"not a duplicate\" verdict: `memberKey` is split from each of `otherKeys` (opaque canonical job keys taken from a cluster's members).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["memberKey", "otherKeys", "autopilotId"]) },
        ],
    },
];
