// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `discovery_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "discovery_search_companies",
        description: "Typeahead search over slug + display name (case-insensitive), starred first then by most-seen.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["query", "atsKind"]) },
        ],
    },
    CatalogueEntry {
        command: "discovery_set_starred",
        description: "Star / unstar a company (materializing a curated-seed row if it was never organically seen).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["atsKind", "slug", "starred"]) },
        ],
    },
    CatalogueEntry {
        command: "discovery_watched",
        description: "Every watched (starred) company.",
        args: &[],
    },
];
