// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `documents_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "documents_export_and_save",
        description: "",
        args: &[
            CatalogueArg { name: "request", required: true, fields: Some(&["text", "format", "documentType", "templateId", "meta", "atsMode", "locale", "contact", "accent", "letterLayoutId"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_export_document",
        description: "",
        args: &[
            CatalogueArg { name: "request", required: true, fields: Some(&["text", "format", "documentType", "templateId", "meta", "atsMode", "locale", "contact", "accent", "letterLayoutId"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_get_text",
        description: "Fetch the stored extracted text for one document by id.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "documents_import",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["name", "bytes", "title", "locale"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "documents_recommend_template",
        description: "Suggest a template + locale from the generation metadata signals.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["jobTitle", "candidateSeniority", "topRequirements", "resumeLanguage", "jobAdLanguage", "targetCountry"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_remove",
        description: "Permanently delete this document (résumé/cover-letter/etc.) from the store — no undo.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "documents_render_preview_images",
        description: "Render the same document to per-page images for the live preview, shown via `<img>` (CSP `img-src 'self' data: blob:`) instead of the PDF→iframe path.",
        args: &[
            CatalogueArg { name: "request", required: true, fields: Some(&["text", "format", "documentType", "templateId", "meta", "atsMode", "locale", "contact", "accent", "letterLayoutId"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_set_default",
        description: "",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
];
