// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `email_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "email_watch_check_now",
        description: "Runs a real fetch+parse+match+notify pass now (the same pass the background poller runs).",
        args: &[],
    },
    CatalogueEntry {
        command: "email_watch_connect",
        description: "Validates by a real IMAP LOGIN + SELECT INBOX before persisting.",
        args: &[
            CatalogueArg { name: "address", required: true, fields: None },
            CatalogueArg { name: "appPassword", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_disconnect",
        description: "Removes the keychain app password and clears the account row.",
        args: &[],
    },
    CatalogueEntry {
        command: "email_watch_set_auto_write_enabled",
        description: "The v2 auto-write opt-in — see `EmailWatchStatus.autoWriteEnabled`.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_set_enabled",
        description: "",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_status",
        description: "",
        args: &[],
    },
];
