// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `extension_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "extension_bridge_ai_assist_enabled",
        description: "Read the AI-answer-assist opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_auto_track_enabled",
        description: "Read the auto-track opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_autofill_enabled",
        description: "Read the assisted-autofill opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_regenerate_token",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_set_ai_assist_enabled",
        description: "Set + persist the AI-answer-assist opt-in; echoes the stored value.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "extension_bridge_set_auto_track_enabled",
        description: "Set + persist the auto-track opt-in; echoes the stored value.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "extension_bridge_set_autofill_enabled",
        description: "Set + persist the assisted-autofill opt-in; echoes the stored value.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "extension_bridge_status",
        description: "",
        args: &[],
    },
];
