// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `generate_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[CatalogueEntry {
    command: "generate_pipeline",
    description: "Stream a generation through the backend orchestration pipeline.",
    args: &[CatalogueArg {
        name: "req",
        required: true,
        fields: Some(&[
            "model",
            "messages",
            "locale",
            "temperature",
            "topP",
            "frequencyPenalty",
            "presencePenalty",
            "repeatPenalty",
            "maxTokens",
            "contextWindow",
            "effort",
            "intent",
        ]),
    }],
}];
