// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `geocode_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "geocode_suggest",
        description: "Location autocomplete, filtered to city-level and country-level results only (`to_city_country` in `apps/desktop/src-tauri/src/commands/geocoding.rs`) — a street or a venue is never a job-search location.",
        args: &[
            CatalogueArg { name: "query", required: true, fields: None },
        ],
    },
];
