// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `github_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[CatalogueEntry {
    command: "github_import_repos",
    description:
        "Fetch a user's public repos. `input` is a bare username or a `github.com/<user>` URL.",
    args: &[CatalogueArg {
        name: "input",
        required: true,
        fields: None,
    }],
}];
