// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `help_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "help_search",
        description: "Rank renderer-supplied help entries against a user question — the retrieval half of the in-app help chat (ADR-043).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["queryId", "locale", "query", "entries", "limit"]) },
        ],
    },
];
