// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `job_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "job_preferences_get",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "job_preferences_set",
        description: "Writes the preference row with MERGE semantics: a key the body OMITS keeps its stored value, a key sent as explicit `null` CLEARS that column.",
        args: &[
            CatalogueArg { name: "prefs", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_set_extra_agency_companies",
        description: "Single-column extra-agency-companies write (ADR-029 §i) — like `setSalaryExpectation`, this NEVER touches the other columns, so an agency-list edit can't overwrite the user's saved location/techStack/ countryCode/salaryExpectation with a stale spread (PR #695 pattern).",
        args: &[
            CatalogueArg { name: "companies", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_set_salary_expectation",
        description: "Single-column salary-expectation write (review fix, PR #695) — unlike `set()`, this addresses exactly one column, so it can never carry a stale copy of another.",
        args: &[
            CatalogueArg { name: "salaryExpectation", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_set_semantic_scoring",
        description: "Single-column mirror of the renderer's `semanticScoring` preference (ADR-020 addendum).",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
];
