// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `jobs_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "jobs_cancel",
        description: "",
        args: &[CatalogueArg {
            name: "jobId",
            required: true,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "jobs_get",
        description: "",
        args: &[CatalogueArg {
            name: "jobId",
            required: true,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "jobs_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "jobs_retry",
        description: "",
        args: &[CatalogueArg {
            name: "jobId",
            required: true,
            fields: None,
        }],
    },
];
