// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `match_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "match_resume",
        description: "Score one résumé against one job. The single scoring path: the jobs list asks for a score per row as that row renders, rather than running one pass over everything (the one-shot `match_resume_batch` command was removed — it had no consumers).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["resumeId", "jobId", "semanticScoringEnabled"]) },
        ],
    },
    CatalogueEntry {
        command: "match_resume_text",
        description: "Score one résumé against arbitrary job-ad TEXT — for a caller with a `jobDesc: string` in hand but no `PostingsCache` id (e.g. the Score tab in `JobAdView`, whose `TailorFlow` parent receives an `Application` / `AutopilotFoundJob`, neither of which carries one).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["resumeId", "jobText", "semanticScoringEnabled"]) },
        ],
    },
];
