// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `menu_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::CatalogueEntry;

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "menu_take_pending",
        description: "Atomically take + clear the menu intent buffered by the shell while the window was hidden/minimized (close-to-tray).",
        args: &[],
    },
];
