// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `notifications_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "notifications_clear_all",
        description: "Permanently delete every notification in the inbox — no selector, no undo.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_clicked",
        description: "Invokes `notifications_clicked` — focuses the window and opens the inbox.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_mark_all_read",
        description: "Mark every notification in the inbox read — no \"mark unread\" path exists, so this cannot be undone.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_mark_read",
        description: "Mark one notification read by id — no \"mark unread\" path exists, so this cannot be undone.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "notifications_remove",
        description: "Permanently delete one notification from the inbox by id.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
];
