// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `privacy_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "privacy_clear_interactions",
        description: "Clear all saved job interaction history (applied, viewed, bookmarked).",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_get_crash_reporting",
        description: "Current crash-reporting consent state.",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_reset_app",
        description: "Factory reset: sign out all boards, clear all cached data.",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_set_crash_reporting",
        description: "Persist crash-reporting consent.",
        args: &[CatalogueArg {
            name: "settings",
            required: true,
            fields: Some(&["enabled", "consentShown"]),
        }],
    },
    CatalogueEntry {
        command: "privacy_sign_out_all",
        description: "Sign out all connected accounts by wiping Chromium profiles.",
        args: &[],
    },
];
