// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `profile_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[CatalogueEntry {
    command: "profile_import_from_url",
    description: "Fetch a LinkedIn profile URL and return extracted resume text.",
    args: &[CatalogueArg {
        name: "url",
        required: true,
        fields: None,
    }],
}];
