// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `referrals_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "referrals_list",
        description: "All referral contacts, optionally filtered to one job's `jobUrl`.",
        args: &[CatalogueArg {
            name: "jobUrl",
            required: false,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "referrals_remove",
        description: "Permanently delete one referral contact by id — the drafts on it go with it.",
        args: &[CatalogueArg {
            name: "id",
            required: true,
            fields: None,
        }],
    },
    CatalogueEntry {
        command: "referrals_upsert",
        description: "Create or update a contact; resolves to the stored record.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: Some(&[
                "id",
                "jobUrl",
                "companyName",
                "personName",
                "personRole",
                "linkedinUrl",
                "emailDraft",
                "messageDraft",
                "inviteNoteDraft",
                "channel",
                "status",
                "notes",
            ]),
        }],
    },
];
