// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `resume_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "resume_extract_text",
        description: "Extract plain text from an uploaded resume/job-ad file (pdf, docx, txt, md).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["name", "bytes"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_get",
        description: "One run with its full stage trail. `null` for an unknown id.",
        args: &[
            CatalogueArg { name: "runId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_list_for_job",
        description: "The retained runs for one posting, newest first — at most `RETENTION_RUNS_PER_JOB` (3), which is what the backend keeps.",
        args: &[
            CatalogueArg { name: "jobUrl", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_regenerate_section",
        description: "Re-generate ONE section of a finished run and splice it back in, through the same primitive the repair loop uses.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["runId", "sectionKey", "note"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_resolve_fabrication",
        description: "Record the user's Remove/Keep verdict on ONE surviving fabrication finding.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["runId", "issueKey", "decision"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_run",
        description: "Start one staged run. Resolves as soon as the run is admitted (the concurrency wait happens inside the run, so a queued run still returns its ids immediately).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "resume_trim_suggestions",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["resumeText", "jobText", "locale"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_validate_content",
        description: "Deterministic content-quality checks (factual accuracy, ATS structure, AI-voice tells) on an already-generated résumé/letter against its source résumé and the job ad.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["generated", "source", "jobAd", "topRequirements", "targetLanguage", "docKind"]) },
        ],
    },
];
