// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `scrape_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "scrape_boards",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["boards", "query", "location", "amount", "replace", "dateFilter", "countryCode", "latitude", "longitude", "radiusKm", "jobType", "workTypes", "experienceLevel", "easyApply", "activelyHiring", "verified", "sortBy", "companies"]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_clear_postings",
        description: "Permanently wipe the entire cached postings list — no selector, no undo; interaction history is unaffected.",
        args: &[],
    },
    CatalogueEntry {
        command: "scrape_hybrid_search",
        description: "Rank the live postings cache (or a caller-supplied eligible subset of it) by lexical + optional dense relevance to a query — see `commands::hybrid_search` (Rust) for the lexical/dense/fusion/rerank pipeline.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["queryId", "query", "eligibleIds", "limit"]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_list_interactions",
        description: "",
        args: &[
            CatalogueArg { name: "filter", required: false, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_list_postings",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "scrape_persist_job",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_remove_interaction",
        description: "Delete a persisted interaction — the real \"undo\" for `persistJob`, e.g.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_resolve_url",
        description: "Resolve a single posting (incl. full description) from its URL.",
        args: &[
            CatalogueArg { name: "url", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "scrape_update_description",
        description: "Write a freshly-resolved full description back into every store that can carry a copy of this posting, addressed by `url` (not a board-synthetic posting id — no reader outside the live cache can supply that): the live postings cache AND every matching found-job row persisted by an autopilot, so the match scorer reads the full text instead of the truncated aggregator snippet wherever the posting was surfaced from.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_url",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["url"]) },
        ],
    },
];
