// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Shard 5 of 5 of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::CatalogueEntry;

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "updater_check",
        description: "Trigger a check. Resolves with the outcome (also emitted on `onStatus`).",
        args: &[],
    },
    CatalogueEntry {
        command: "updater_download",
        description: "Download the update `check` found. Resolves either way — the shell reports failure on the `updater:status` stream, not by rejecting.",
        args: &[],
    },
    CatalogueEntry {
        command: "updater_install",
        description: "Install the downloaded update and relaunch.",
        args: &[],
    },
];
