// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Shard 2 of 3 of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "documents_recommend_template",
        description: "Suggest a template + locale from the generation metadata signals.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[
                "jobTitle",
                "candidateSeniority",
                "topRequirements",
                "resumeLanguage",
                "jobAdLanguage",
                "targetCountry",
            ],
        }],
    },
    CatalogueEntry {
        command: "documents_remove",
        description: "",
        args: &[CatalogueArg {
            name: "id",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "documents_render_preview_images",
        description: "Render the same document to per-page images for the live preview, shown via `<img>` (CSP `img-src 'self' data:",
        args: &[CatalogueArg {
            name: "request",
            required: true,
            fields: &[
                "text",
                "format",
                "documentType",
                "templateId",
                "meta",
                "atsMode",
                "locale",
                "contact",
                "accent",
                "letterLayoutId",
            ],
        }],
    },
    CatalogueEntry {
        command: "documents_set_default",
        description: "",
        args: &[CatalogueArg {
            name: "id",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "email_watch_check_now",
        description: "Runs a real fetch+parse+match+notify pass now (the same pass the background poller runs).",
        args: &[],
    },
    CatalogueEntry {
        command: "email_watch_connect",
        description: "Validates by a real IMAP LOGIN + SELECT INBOX before persisting.",
        args: &[
            CatalogueArg {
                name: "address",
                required: true,
                fields: &[],
            },
            CatalogueArg {
                name: "appPassword",
                required: true,
                fields: &[],
            },
        ],
    },
    CatalogueEntry {
        command: "email_watch_disconnect",
        description: "Removes the keychain app password and clears the account row.",
        args: &[],
    },
    CatalogueEntry {
        command: "email_watch_set_auto_write_enabled",
        description: "The v2 auto-write opt-in — see `EmailWatchStatus.autoWriteEnabled`.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "email_watch_set_enabled",
        description: "",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "email_watch_status",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_ai_assist_enabled",
        description: "Read the AI-answer-assist opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_auto_track_enabled",
        description: "Read the auto-track opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_autofill_enabled",
        description: "Read the assisted-autofill opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_regenerate_token",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_set_ai_assist_enabled",
        description: "Set + persist the AI-answer-assist opt-in; echoes the stored value.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "extension_bridge_set_auto_track_enabled",
        description: "Set + persist the auto-track opt-in; echoes the stored value.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "extension_bridge_set_autofill_enabled",
        description: "Set + persist the assisted-autofill opt-in; echoes the stored value.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "extension_bridge_status",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "generate_pipeline",
        description: "Stream a generation through the backend orchestration pipeline.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[
                "model",
                "messages",
                "locale",
                "temperature",
                "topP",
                "frequencyPenalty",
                "presencePenalty",
                "repeatPenalty",
                "maxTokens",
                "contextWindow",
                "effort",
                "intent",
            ],
        }],
    },
    CatalogueEntry {
        command: "geocode_suggest",
        description: "Location autocomplete, filtered to city-level and country-level results only (`to_city_country` in `apps/desktop/src-tauri/src/commands/geocoding.rs`) — a street or a venue is never a job-search location.",
        args: &[CatalogueArg {
            name: "query",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "github_import_repos",
        description: "Fetch a user's public repos.",
        args: &[CatalogueArg {
            name: "input",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "help_search",
        description: "Rank renderer-supplied help entries against a user question — the retrieval half of the in-app help chat (ADR-043).",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["queryId", "locale", "query", "entries", "limit"],
        }],
    },
    CatalogueEntry {
        command: "job_preferences_get",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "job_preferences_set",
        description: "Writes the preference row with MERGE semantics:",
        args: &[CatalogueArg {
            name: "prefs",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "job_preferences_set_extra_agency_companies",
        description: "Single-column extra-agency-companies write (ADR-029 §i) — like `setSalaryExpectation`, this NEVER touches the other columns, so an agency-list edit can't overwrite the user's saved location/techStack/ countryCode/salaryExpectation with a stale spread (PR #695 pattern).",
        args: &[CatalogueArg {
            name: "companies",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "job_preferences_set_salary_expectation",
        description: "Single-column salary-expectation write (review fix, PR #695) — unlike `set()`, this addresses exactly one column, so it can never carry a stale copy of another.",
        args: &[CatalogueArg {
            name: "salaryExpectation",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "job_preferences_set_semantic_scoring",
        description: "Single-column mirror of the renderer's `semanticScoring` preference (ADR-020 addendum).",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "jobs_cancel",
        description: "",
        args: &[CatalogueArg {
            name: "jobId",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "jobs_get",
        description: "",
        args: &[CatalogueArg {
            name: "jobId",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "jobs_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "jobs_retry",
        description: "",
        args: &[CatalogueArg {
            name: "jobId",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "match_resume",
        description: "Score one résumé against one job.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["resumeId", "jobId", "semanticScoringEnabled"],
        }],
    },
    CatalogueEntry {
        command: "match_resume_text",
        description: "Score one résumé against arbitrary job-ad TEXT — for a caller with a `jobDesc:",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["resumeId", "jobText", "semanticScoringEnabled"],
        }],
    },
    CatalogueEntry {
        command: "menu_take_pending",
        description: "Atomically take + clear the menu intent buffered by the shell while the window was hidden/minimized (close-to-tray).",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_clear_all",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_clicked",
        description: "Invokes `notifications_clicked` — focuses the window and opens the inbox.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_mark_all_read",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_mark_read",
        description: "",
        args: &[CatalogueArg {
            name: "id",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "notifications_remove",
        description: "",
        args: &[CatalogueArg {
            name: "id",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "privacy_clear_interactions",
        description: "Clear all saved job interaction history (applied, viewed, bookmarked).",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_get_crash_reporting",
        description: "Current crash-reporting consent state.",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_reset_app",
        description: "Factory reset:",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_set_crash_reporting",
        description: "Persist crash-reporting consent.",
        args: &[CatalogueArg {
            name: "settings",
            required: true,
            fields: &["enabled", "consentShown"],
        }],
    },
    CatalogueEntry {
        command: "privacy_sign_out_all",
        description: "Sign out all connected accounts by wiping Chromium profiles.",
        args: &[],
    },
    CatalogueEntry {
        command: "profile_import_from_url",
        description: "Fetch a LinkedIn profile URL and return extracted resume text.",
        args: &[CatalogueArg {
            name: "url",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "referrals_list",
        description: "All referral contacts, optionally filtered to one job's `jobUrl`.",
        args: &[CatalogueArg {
            name: "jobUrl",
            required: false,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "referrals_remove",
        description: "",
        args: &[CatalogueArg {
            name: "id",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "referrals_upsert",
        description: "Create or update a contact; resolves to the stored record.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[
                "id",
                "jobUrl",
                "companyName",
                "personName",
                "personRole",
                "linkedinUrl",
                "emailDraft",
                "messageDraft",
                "inviteNoteDraft",
                "channel",
                "status",
                "notes",
            ],
        }],
    },
    CatalogueEntry {
        command: "resume_extract_text",
        description: "Extract plain text from an uploaded resume/job-ad file (pdf, docx, txt, md).",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["name", "bytes"],
        }],
    },
    CatalogueEntry {
        command: "resume_pipeline_get",
        description: "One run with its full stage trail.",
        args: &[CatalogueArg {
            name: "runId",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "resume_pipeline_list_for_job",
        description: "The retained runs for one posting, newest first — at most `RETENTION_RUNS_PER_JOB` (3), which is what the backend keeps.",
        args: &[CatalogueArg {
            name: "jobUrl",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "resume_pipeline_regenerate_section",
        description: "Re-generate ONE section of a finished run and splice it back in, through the same primitive the repair loop uses.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["runId", "sectionKey", "note"],
        }],
    },
    CatalogueEntry {
        command: "resume_pipeline_resolve_fabrication",
        description: "Record the user's Remove/Keep verdict on ONE surviving fabrication finding.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["runId", "issueKey", "decision"],
        }],
    },
    CatalogueEntry {
        command: "resume_pipeline_run",
        description: "Start one staged run.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "resume_trim_suggestions",
        description: "",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["resumeText", "jobText", "locale"],
        }],
    },
    CatalogueEntry {
        command: "resume_validate_content",
        description: "Deterministic content-quality checks (factual accuracy, ATS structure, AI-voice tells) on an already-generated résumé/letter against its source résumé and the job ad.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[
                "generated",
                "source",
                "jobAd",
                "topRequirements",
                "targetLanguage",
                "docKind",
            ],
        }],
    },
    CatalogueEntry {
        command: "scrape_boards",
        description: "",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[
                "boards",
                "query",
                "location",
                "amount",
                "replace",
                "dateFilter",
                "countryCode",
                "latitude",
                "longitude",
                "radiusKm",
                "jobType",
                "workTypes",
                "experienceLevel",
                "easyApply",
                "activelyHiring",
                "verified",
                "sortBy",
                "companies",
            ],
        }],
    },
    CatalogueEntry {
        command: "scrape_clear_postings",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "scrape_hybrid_search",
        description: "Rank the live postings cache (or a caller-supplied eligible subset of it) by lexical + optional dense relevance to a query — see `commands::hybrid_search` (Rust) for the lexical/dense/fusion/rerank pipeline.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["queryId", "query", "eligibleIds", "limit"],
        }],
    },
    CatalogueEntry {
        command: "scrape_list_interactions",
        description: "",
        args: &[CatalogueArg {
            name: "filter",
            required: false,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "scrape_list_postings",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "scrape_persist_job",
        description: "",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "scrape_remove_interaction",
        description: "Delete a persisted interaction — the real \"undo\" for `persistJob`, e.g.",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "scrape_resolve_url",
        description: "Resolve a single posting (incl.",
        args: &[CatalogueArg {
            name: "url",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "scrape_update_description",
        description: "Write a freshly-resolved full description back into every store that can carry a copy of this posting, addressed by `url` (not a board-synthetic posting id — no reader outside the live cache can supply that):",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "scrape_url",
        description: "",
        args: &[CatalogueArg {
            name: "req",
            required: true,
            fields: &["url"],
        }],
    },
    CatalogueEntry {
        command: "support_export_diagnostics",
        description: "Build and save a redacted diagnostics zip to the caller-supplied path",
        args: &[CatalogueArg {
            name: "dest",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "system_accent_color",
        description: "Best-effort OS accent color.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_agent_cli_info",
        description: "Where this app's own binary lives, as the user should TYPE it when registering the bundled agent CLI / MCP server with a coding agent.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_check_browser",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_launch_at_login",
        description: "Whether the app is registered to launch at login (default off).",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_locale",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_metrics",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_platform",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_protocol_version",
        description: "Returns the IPC protocol version string from the Tauri shell.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_version",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_health",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_open_devtools",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_open_external",
        description: "",
        args: &[CatalogueArg {
            name: "url",
            required: true,
            fields: &[],
        }],
    },
];
