// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Shard 2 of 5 of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "applications_reject_status_event",
        description: "Reject the SPECIFIC email-derived, unconfirmed status-event row `eventId` names — reverts the status by compare-and-set (never clobbers a status that moved on, whether by the user's own hand or a later email, in the meantime) and appends a reversal event.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
            CatalogueArg { name: "eventId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_save_from_posting",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["jobUrl", "board", "company", "title", "candidate", "jobDescription", "salaryMin", "salaryMax", "salaryCurrency"]) },
        ],
    },
    CatalogueEntry {
        command: "applications_set_status",
        description: "Transition the status, optionally recording a free-text `note` — persisted on the appended `status_events` row and returned as `StatusEvent.note` by `get()` (the interaction log).",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
            CatalogueArg { name: "status", required: true, fields: None },
            CatalogueArg { name: "note", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "applications_track",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["jobUrl", "board", "company", "title", "candidate", "jobDescription", "salaryMin", "salaryMax", "salaryCurrency"]) },
        ],
    },
    CatalogueEntry {
        command: "applications_update",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["id", "notes", "nextActionAt", "comp", "contactName", "contactEmail", "jobDescription", "jobSummary", "recipientName", "recipientEmail"]) },
        ],
    },
    CatalogueEntry {
        command: "autopilot_best_matches",
        description: "The current top-scoring matches across every non-archived autopilot, recomputed at query time (nothing about this list is persisted).",
        args: &[],
    },
    CatalogueEntry {
        command: "autopilot_create",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["name", "target", "filter", "schedule", "scheduleHour", "scheduleMinute", "resumeText", "coverLetter", "assistant", "assistantProvider", "assistantModel", "assistantBaseUrl"]) },
        ],
    },
    CatalogueEntry {
        command: "autopilot_get",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "autopilot_pause",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_remove",
        description: "Permanently delete this autopilot and stop its scheduled runs — the found-jobs history it built goes with it.",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_resume",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_run",
        description: "Run an autopilot now. The backend command *resolves* (does not reject) with an `{ error }` payload on a scrape failure or unknown id, so callers MUST inspect `error` — a resolved value is not proof of success.",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "autopilot_take_pending_focus",
        description: "Atomically take + clear the autopilot-focus intent buffered by the shell.",
        args: &[],
    },
    CatalogueEntry {
        command: "autopilot_update",
        description: "",
        args: &[
            CatalogueArg { name: "autopilotId", required: true, fields: None },
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "boards_catalog",
        description: "Full scraper catalog (id, label, mode, auth tier, listed) from the registry — `SCRAPERS` in `apps/desktop/src-tauri/src/scraping/boards/mod.rs`, whose per-scraper `Scraper` impl owns the auth tier and the listed flag.",
        args: &[],
    },
    CatalogueEntry {
        command: "boards_get_status",
        description: "Get current connection status for a board.",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "boards_health",
        description: "Live per-board reliability across runs (Track B1).",
        args: &[],
    },
    CatalogueEntry {
        command: "boards_import_cookies",
        description: "Try to import session cookies from the user's installed Chromium browsers (Chrome, Edge, Brave), so the user can skip the in-app re-login.",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "boards_login_with_browser",
        description: "Connect to a board by launching a browser for manual login.",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "boards_logout",
        description: "Disconnect a board (closes context only; does not delete profile).",
        args: &[
            CatalogueArg { name: "boardId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "cli_agents_redetect",
        description: "Clear the detection cache and re-probe (call after an install).",
        args: &[],
    },
    CatalogueEntry {
        command: "cli_agents_status",
        description: "Cached install status for every CLI agent (+ npm availability).",
        args: &[],
    },
    CatalogueEntry {
        command: "contact_profile_get",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "contact_profile_header_line",
        description: "The stored profile's header contact line as markdown, localized for `lang` — built by the single shared `ContactProfile::header_markdown` (Rust), never re-implemented here, so the ordering rules can't drift between the two languages.",
        args: &[
            CatalogueArg { name: "lang", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "contact_profile_set",
        description: "Rejects on failure (unmanaged store, invalid payload, storage error) — there is no in-band `{ error }` shape to inspect.",
        args: &[
            CatalogueArg { name: "profile", required: true, fields: Some(&["fullName", "email", "phone", "location", "linkedin", "github", "website", "extraLinks", "photo"]) },
        ],
    },
    CatalogueEntry {
        command: "credentials_available",
        description: "Whether the OS supports encrypted secret storage.",
        args: &[],
    },
    CatalogueEntry {
        command: "data_export",
        description: "Export all user data to a user-chosen JSON file.",
        args: &[],
    },
    CatalogueEntry {
        command: "data_import",
        description: "Restore all user data from a user-chosen backup file (replace semantics).",
        args: &[],
    },
    CatalogueEntry {
        command: "dedup_mark_not_duplicate",
        description: "Record a \"not a duplicate\" verdict: `memberKey` is split from each of `otherKeys` (opaque canonical job keys taken from a cluster's members).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["memberKey", "otherKeys", "autopilotId"]) },
        ],
    },
    CatalogueEntry {
        command: "discovery_search_companies",
        description: "Typeahead search over slug + display name (case-insensitive), starred first then by most-seen.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["query", "atsKind"]) },
        ],
    },
    CatalogueEntry {
        command: "discovery_set_starred",
        description: "Star / unstar a company (materializing a curated-seed row if it was never organically seen).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["atsKind", "slug", "starred"]) },
        ],
    },
    CatalogueEntry {
        command: "discovery_watched",
        description: "Every watched (starred) company.",
        args: &[],
    },
    CatalogueEntry {
        command: "documents_export_and_save",
        description: "",
        args: &[
            CatalogueArg { name: "request", required: true, fields: Some(&["text", "format", "documentType", "templateId", "meta", "atsMode", "locale", "contact", "accent", "letterLayoutId"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_export_document",
        description: "",
        args: &[
            CatalogueArg { name: "request", required: true, fields: Some(&["text", "format", "documentType", "templateId", "meta", "atsMode", "locale", "contact", "accent", "letterLayoutId"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_get_text",
        description: "Fetch the stored extracted text for one document by id.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "documents_import",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["name", "bytes", "title", "locale"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "documents_recommend_template",
        description: "Suggest a template + locale from the generation metadata signals.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["jobTitle", "candidateSeniority", "topRequirements", "resumeLanguage", "jobAdLanguage", "targetCountry"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_remove",
        description: "Permanently delete this document (résumé/cover-letter/etc.) from the store — no undo.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
];
