// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Shard 4 of 5 of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "privacy_sign_out_all",
        description: "Sign out all connected accounts by wiping Chromium profiles.",
        args: &[],
    },
    CatalogueEntry {
        command: "profile_import_from_url",
        description: "Fetch a LinkedIn profile URL and return extracted resume text.",
        args: &[
            CatalogueArg { name: "url", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "referrals_list",
        description: "All referral contacts, optionally filtered to one job's `jobUrl`.",
        args: &[
            CatalogueArg { name: "jobUrl", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "referrals_remove",
        description: "Permanently delete one referral contact by id — the drafts on it go with it.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "referrals_upsert",
        description: "Create or update a contact; resolves to the stored record.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["id", "jobUrl", "companyName", "personName", "personRole", "linkedinUrl", "emailDraft", "messageDraft", "inviteNoteDraft", "channel", "status", "notes"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_extract_text",
        description: "Extract plain text from an uploaded resume/job-ad file (pdf, docx, txt, md).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["name", "bytes"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_get",
        description: "One run with its full stage trail. `null` for an unknown id.",
        args: &[
            CatalogueArg { name: "runId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_list_for_job",
        description: "The retained runs for one posting, newest first — at most `RETENTION_RUNS_PER_JOB` (3), which is what the backend keeps.",
        args: &[
            CatalogueArg { name: "jobUrl", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_regenerate_section",
        description: "Re-generate ONE section of a finished run and splice it back in, through the same primitive the repair loop uses.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["runId", "sectionKey", "note"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_resolve_fabrication",
        description: "Record the user's Remove/Keep verdict on ONE surviving fabrication finding.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["runId", "issueKey", "decision"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_pipeline_run",
        description: "Start one staged run. Resolves as soon as the run is admitted (the concurrency wait happens inside the run, so a queued run still returns its ids immediately).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "resume_trim_suggestions",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["resumeText", "jobText", "locale"]) },
        ],
    },
    CatalogueEntry {
        command: "resume_validate_content",
        description: "Deterministic content-quality checks (factual accuracy, ATS structure, AI-voice tells) on an already-generated résumé/letter against its source résumé and the job ad.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["generated", "source", "jobAd", "topRequirements", "targetLanguage", "docKind"]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_boards",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["boards", "query", "location", "amount", "replace", "dateFilter", "countryCode", "latitude", "longitude", "radiusKm", "jobType", "workTypes", "experienceLevel", "easyApply", "activelyHiring", "verified", "sortBy", "companies"]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_clear_postings",
        description: "Permanently wipe the entire cached postings list — no selector, no undo; interaction history is unaffected.",
        args: &[],
    },
    CatalogueEntry {
        command: "scrape_hybrid_search",
        description: "Rank the live postings cache (or a caller-supplied eligible subset of it) by lexical + optional dense relevance to a query — see `commands::hybrid_search` (Rust) for the lexical/dense/fusion/rerank pipeline.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["queryId", "query", "eligibleIds", "limit"]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_list_interactions",
        description: "",
        args: &[
            CatalogueArg { name: "filter", required: false, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_list_postings",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "scrape_persist_job",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_remove_interaction",
        description: "Delete a persisted interaction — the real \"undo\" for `persistJob`, e.g.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_resolve_url",
        description: "Resolve a single posting (incl. full description) from its URL.",
        args: &[
            CatalogueArg { name: "url", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "scrape_update_description",
        description: "Write a freshly-resolved full description back into every store that can carry a copy of this posting, addressed by `url` (not a board-synthetic posting id — no reader outside the live cache can supply that): the live postings cache AND every matching found-job row persisted by an autopilot, so the match scorer reads the full text instead of the truncated aggregator snippet wherever the posting was surfaced from.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "scrape_url",
        description: "",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["url"]) },
        ],
    },
    CatalogueEntry {
        command: "support_export_diagnostics",
        description: "Build and save a redacted diagnostics zip to the caller-supplied path",
        args: &[
            CatalogueArg { name: "dest", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_accent_color",
        description: "Best-effort OS accent color. `supported` is true only where we can read it (Windows, macOS); elsewhere `color` is null and the renderer keeps the Default accent.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_agent_cli_info",
        description: "Where this app's own binary lives, as the user should TYPE it when registering the bundled agent CLI / MCP server with a coding agent.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_check_browser",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_launch_at_login",
        description: "Whether the app is registered to launch at login (default off).",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_locale",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_metrics",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_platform",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_protocol_version",
        description: "Returns the IPC protocol version string from the Tauri shell.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_version",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_health",
        description: "Runtime health snapshot. Two AI-related blocks answer two different questions: `ai` is the LOCAL Ollama daemon probe (`scope: 'localOllama'`) — reachable + which model is loaded — while `activeProvider` is the app's actually-configured generation provider/model (same lookup as `ai.getActiveConfig`), which may be a cloud provider unrelated to Ollama's reachability.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_open_devtools",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_open_external",
        description: "Open `url` in the OS default handler (browser/app) — outside this app's own sandbox.",
        args: &[
            CatalogueArg { name: "url", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_close_to_tray",
        description: "Push the close-to-tray preference to the shell.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_launch_at_login",
        description: "Enable/disable launch-at-login; resolves to the resulting OS state.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_locale",
        description: "",
        args: &[
            CatalogueArg { name: "locale", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_performance_mode",
        description: "",
        args: &[
            CatalogueArg { name: "config", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "updater_changelog",
        description: "Recent release history (newest first) for the in-app changelog.",
        args: &[],
    },
];
