// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Shard 3 of 5 of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "documents_render_preview_images",
        description: "Render the same document to per-page images for the live preview, shown via `<img>` (CSP `img-src 'self' data: blob:`) instead of the PDF→iframe path.",
        args: &[
            CatalogueArg { name: "request", required: true, fields: Some(&["text", "format", "documentType", "templateId", "meta", "atsMode", "locale", "contact", "accent", "letterLayoutId"]) },
        ],
    },
    CatalogueEntry {
        command: "documents_set_default",
        description: "",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_check_now",
        description: "Runs a real fetch+parse+match+notify pass now (the same pass the background poller runs).",
        args: &[],
    },
    CatalogueEntry {
        command: "email_watch_connect",
        description: "Validates by a real IMAP LOGIN + SELECT INBOX before persisting.",
        args: &[
            CatalogueArg { name: "address", required: true, fields: None },
            CatalogueArg { name: "appPassword", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_disconnect",
        description: "Removes the keychain app password and clears the account row.",
        args: &[],
    },
    CatalogueEntry {
        command: "email_watch_set_auto_write_enabled",
        description: "The v2 auto-write opt-in — see `EmailWatchStatus.autoWriteEnabled`.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_set_enabled",
        description: "",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "email_watch_status",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_ai_assist_enabled",
        description: "Read the AI-answer-assist opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_auto_track_enabled",
        description: "Read the auto-track opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_autofill_enabled",
        description: "Read the assisted-autofill opt-in (default OFF).",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_regenerate_token",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "extension_bridge_set_ai_assist_enabled",
        description: "Set + persist the AI-answer-assist opt-in; echoes the stored value.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "extension_bridge_set_auto_track_enabled",
        description: "Set + persist the auto-track opt-in; echoes the stored value.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "extension_bridge_set_autofill_enabled",
        description: "Set + persist the assisted-autofill opt-in; echoes the stored value.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "extension_bridge_status",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "generate_pipeline",
        description: "Stream a generation through the backend orchestration pipeline.",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["model", "messages", "locale", "temperature", "topP", "frequencyPenalty", "presencePenalty", "repeatPenalty", "maxTokens", "contextWindow", "effort", "intent"]) },
        ],
    },
    CatalogueEntry {
        command: "geocode_suggest",
        description: "Location autocomplete, filtered to city-level and country-level results only (`to_city_country` in `apps/desktop/src-tauri/src/commands/geocoding.rs`) — a street or a venue is never a job-search location.",
        args: &[
            CatalogueArg { name: "query", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "github_import_repos",
        description: "Fetch a user's public repos. `input` is a bare username or a `github.com/<user>` URL.",
        args: &[
            CatalogueArg { name: "input", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "help_search",
        description: "Rank renderer-supplied help entries against a user question — the retrieval half of the in-app help chat (ADR-043).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["queryId", "locale", "query", "entries", "limit"]) },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_get",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "job_preferences_set",
        description: "Writes the preference row with MERGE semantics: a key the body OMITS keeps its stored value, a key sent as explicit `null` CLEARS that column.",
        args: &[
            CatalogueArg { name: "prefs", required: true, fields: Some(&[]) },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_set_extra_agency_companies",
        description: "Single-column extra-agency-companies write (ADR-029 §i) — like `setSalaryExpectation`, this NEVER touches the other columns, so an agency-list edit can't overwrite the user's saved location/techStack/ countryCode/salaryExpectation with a stale spread (PR #695 pattern).",
        args: &[
            CatalogueArg { name: "companies", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_set_salary_expectation",
        description: "Single-column salary-expectation write (review fix, PR #695) — unlike `set()`, this addresses exactly one column, so it can never carry a stale copy of another.",
        args: &[
            CatalogueArg { name: "salaryExpectation", required: false, fields: None },
        ],
    },
    CatalogueEntry {
        command: "job_preferences_set_semantic_scoring",
        description: "Single-column mirror of the renderer's `semanticScoring` preference (ADR-020 addendum).",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "jobs_cancel",
        description: "",
        args: &[
            CatalogueArg { name: "jobId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "jobs_get",
        description: "",
        args: &[
            CatalogueArg { name: "jobId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "jobs_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "jobs_retry",
        description: "",
        args: &[
            CatalogueArg { name: "jobId", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "match_resume",
        description: "Score one résumé against one job. The single scoring path: the jobs list asks for a score per row as that row renders, rather than running one pass over everything (the one-shot `match_resume_batch` command was removed — it had no consumers).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["resumeId", "jobId", "semanticScoringEnabled"]) },
        ],
    },
    CatalogueEntry {
        command: "match_resume_text",
        description: "Score one résumé against arbitrary job-ad TEXT — for a caller with a `jobDesc: string` in hand but no `PostingsCache` id (e.g. the Score tab in `JobAdView`, whose `TailorFlow` parent receives an `Application` / `AutopilotFoundJob`, neither of which carries one).",
        args: &[
            CatalogueArg { name: "req", required: true, fields: Some(&["resumeId", "jobText", "semanticScoringEnabled"]) },
        ],
    },
    CatalogueEntry {
        command: "menu_take_pending",
        description: "Atomically take + clear the menu intent buffered by the shell while the window was hidden/minimized (close-to-tray).",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_clear_all",
        description: "Permanently delete every notification in the inbox — no selector, no undo.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_clicked",
        description: "Invokes `notifications_clicked` — focuses the window and opens the inbox.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_list",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_mark_all_read",
        description: "Mark every notification in the inbox read — no \"mark unread\" path exists, so this cannot be undone.",
        args: &[],
    },
    CatalogueEntry {
        command: "notifications_mark_read",
        description: "Mark one notification read by id — no \"mark unread\" path exists, so this cannot be undone.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "notifications_remove",
        description: "Permanently delete one notification from the inbox by id.",
        args: &[
            CatalogueArg { name: "id", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "privacy_clear_interactions",
        description: "Clear all saved job interaction history (applied, viewed, bookmarked).",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_get_crash_reporting",
        description: "Current crash-reporting consent state.",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_reset_app",
        description: "Factory reset: sign out all boards, clear all cached data.",
        args: &[],
    },
    CatalogueEntry {
        command: "privacy_set_crash_reporting",
        description: "Persist crash-reporting consent.",
        args: &[
            CatalogueArg { name: "settings", required: true, fields: Some(&["enabled", "consentShown"]) },
        ],
    },
];
