// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Shard 3 of 3 of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "system_set_close_to_tray",
        description: "Push the close-to-tray preference to the shell.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "system_set_launch_at_login",
        description: "Enable/disable launch-at-login; resolves to the resulting OS state.",
        args: &[CatalogueArg {
            name: "enabled",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "system_set_locale",
        description: "",
        args: &[CatalogueArg {
            name: "locale",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "system_set_performance_mode",
        description: "",
        args: &[CatalogueArg {
            name: "config",
            required: true,
            fields: &[],
        }],
    },
    CatalogueEntry {
        command: "updater_changelog",
        description: "Recent release history (newest first) for the in-app changelog.",
        args: &[],
    },
    CatalogueEntry {
        command: "updater_check",
        description: "Trigger a check.",
        args: &[],
    },
    CatalogueEntry {
        command: "updater_download",
        description: "Download the update `check` found.",
        args: &[],
    },
    CatalogueEntry {
        command: "updater_install",
        description: "Install the downloaded update and relaunch.",
        args: &[],
    },
];
