// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `support_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[CatalogueEntry {
    command: "support_export_diagnostics",
    description: "Build and save a redacted diagnostics zip to the caller-supplied path",
    args: &[CatalogueArg {
        name: "dest",
        required: true,
        fields: None,
    }],
}];
