// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// The `system_*` commands of the sharded command catalogue — see
// `../catalogue.rs`'s own doc for why this table is split at all.

use super::{CatalogueArg, CatalogueEntry};

pub(super) const ENTRIES: &[CatalogueEntry] = &[
    CatalogueEntry {
        command: "system_accent_color",
        description: "Best-effort OS accent color. `supported` is true only where we can read it (Windows, macOS); elsewhere `color` is null and the renderer keeps the Default accent.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_agent_cli_info",
        description: "Where this app's own binary lives, as the user should TYPE it when registering the bundled agent CLI / MCP server with a coding agent.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_check_browser",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_launch_at_login",
        description: "Whether the app is registered to launch at login (default off).",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_locale",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_metrics",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_platform",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_protocol_version",
        description: "Returns the IPC protocol version string from the Tauri shell.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_get_version",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_health",
        description: "Runtime health snapshot. Two AI-related blocks answer two different questions: `ai` is the LOCAL Ollama daemon probe (`scope: 'localOllama'`) — reachable + which model is loaded — while `activeProvider` is the app's actually-configured generation provider/model (same lookup as `ai.getActiveConfig`), which may be a cloud provider unrelated to Ollama's reachability.",
        args: &[],
    },
    CatalogueEntry {
        command: "system_open_devtools",
        description: "",
        args: &[],
    },
    CatalogueEntry {
        command: "system_open_external",
        description: "Open `url` in the OS default handler (browser/app) — outside this app's own sandbox.",
        args: &[
            CatalogueArg { name: "url", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_close_to_tray",
        description: "Push the close-to-tray preference to the shell.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_launch_at_login",
        description: "Enable/disable launch-at-login; resolves to the resulting OS state.",
        args: &[
            CatalogueArg { name: "enabled", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_locale",
        description: "",
        args: &[
            CatalogueArg { name: "locale", required: true, fields: None },
        ],
    },
    CatalogueEntry {
        command: "system_set_performance_mode",
        description: "",
        args: &[
            CatalogueArg { name: "config", required: true, fields: Some(&[]) },
        ],
    },
];
