import type { SearchEntry } from './search-entry';

/** General, appearance, contact and AI settings. */
export const CORE_ENTRIES: SearchEntry[] = [
  // ── general ─────────────────────────────────────────────────────────────────
  {
    id: 'general-profile',
    section: 'general',
    titleKey: 'settings.profile.title',
    keywords: ['name', 'display', 'user', 'profile'],
    anchor: 'general-profile',
  },
  {
    id: 'general-language',
    section: 'general',
    titleKey: 'settings.language.title',
    keywords: ['language', 'locale', 'english', 'german', 'deutsch', 'sprache', 'i18n'],
    anchor: 'general-language',
  },
  {
    id: 'general-onboarding',
    section: 'general',
    titleKey: 'settings.onboarding.title',
    keywords: ['onboarding', 'wizard', 'tour', 'replay', 'intro', 'welcome'],
    anchor: 'general-onboarding',
  },
  {
    id: 'general-startup',
    section: 'general',
    titleKey: 'settings.startup.title',
    keywords: ['startup', 'launch', 'login', 'tray', 'boot', 'autostart', 'close'],
    anchor: 'general-startup',
  },
  {
    id: 'general-window',
    section: 'general',
    titleKey: 'settings.window.title',
    keywords: ['window', 'position', 'reset', 'monitor', 'hide', 'move'],
    anchor: 'general-window',
  },
  {
    id: 'general-updates',
    section: 'general',
    titleKey: 'settings.update.title',
    keywords: ['update', 'version', 'upgrade', 'release', 'changelog', 'install'],
    anchor: 'general-updates',
  },

  // ── appearance ───────────────────────────────────────────────────────────────
  {
    id: 'appearance-theme',
    section: 'appearance',
    titleKey: 'settings.appearance.scheme',
    keywords: ['theme', 'dark', 'light', 'system', 'color scheme', 'mode'],
    anchor: 'appearance-theme',
  },
  {
    id: 'appearance-accent',
    section: 'appearance',
    titleKey: 'settings.appearance.accent',
    keywords: ['accent', 'color', 'brand', 'violet', 'blue', 'green', 'pink', 'orange', 'graphite'],
    anchor: 'appearance-accent',
  },
  {
    id: 'appearance-textsize',
    section: 'appearance',
    titleKey: 'settings.appearance.textSize',
    keywords: ['text', 'size', 'font', 'small', 'large', 'scale', 'typography'],
    anchor: 'appearance-textsize',
  },
  {
    id: 'appearance-transparency',
    section: 'appearance',
    titleKey: 'settings.appearance.reduceTransparency',
    keywords: ['transparency', 'glass', 'frosted', 'blur', 'solid'],
    anchor: 'appearance-transparency',
  },
  {
    id: 'appearance-contrast',
    section: 'appearance',
    titleKey: 'settings.appearance.increaseContrast',
    keywords: ['contrast', 'border', 'accessibility', 'a11y', 'visibility'],
    anchor: 'appearance-contrast',
  },

  // ── contact ──────────────────────────────────────────────────────────────────
  {
    id: 'contact-profile',
    section: 'contact',
    titleKey: 'settings.contactProfile.title',
    keywords: [
      'contact',
      'email',
      'phone',
      'name',
      'linkedin',
      'github',
      'website',
      'header',
      'resume',
      'cv',
      'photo',
      'profile',
      'address',
    ],
    anchor: 'contact-profile',
  },
  {
    id: 'contact-applicant',
    section: 'contact',
    titleKey: 'settings.applicant.title',
    keywords: [
      'salary',
      'start date',
      'notice',
      'remote',
      'hybrid',
      'applicant',
      'cover letter',
      'work',
      'compensation',
      'earliest',
    ],
    anchor: 'contact-applicant',
  },

  // ── ai ───────────────────────────────────────────────────────────────────────
  {
    id: 'ai-provider',
    section: 'ai',
    titleKey: 'settings.aiProvider.title',
    keywords: [
      'provider',
      'ollama',
      'openai',
      'claude',
      'anthropic',
      'gemini',
      'groq',
      'mistral',
      'api key',
      'local',
      'cloud',
      'model',
      'llm',
      'gpt',
    ],
    anchor: 'ai-provider',
  },
  {
    id: 'ai-tone',
    section: 'ai',
    titleKey: 'settings.outputTone.title',
    keywords: [
      'tone',
      'style',
      'professional',
      'casual',
      'formal',
      'creative',
      'writing',
      'output',
      'voice',
    ],
    anchor: 'ai-tone',
  },
  {
    id: 'ai-prompt-quality',
    section: 'ai',
    titleKey: 'settings.promptQuality.title',
    keywords: ['prompt', 'quality', 'full', 'auto', 'compact', 'fast', 'verbosity', 'detail'],
    anchor: 'ai-prompt-quality',
  },
  {
    id: 'ai-stages',
    section: 'ai',
    titleKey: 'settings.ai.stages.title',
    keywords: ['stage', 'stages', 'per-stage', 'override', 'draft', 'pipeline', 'model', 'advisor'],
    anchor: 'ai-stages',
  },
  {
    id: 'ai-embeddings',
    section: 'ai',
    titleKey: 'settings.ai.embeddings.title',
    keywords: ['embeddings', 'search', 'matching', 'vector', 'semantic', 'index'],
    anchor: 'ai-embeddings',
  },
  {
    id: 'ai-company-research',
    section: 'ai',
    titleKey: 'settings.companyResearch.title',
    keywords: ['company', 'research', 'web search', 'brief', 'ollama key'],
    anchor: 'ai-company-research',
  },
  {
    id: 'ai-spend',
    section: 'ai',
    titleKey: 'settings.ai.spend.title',
    keywords: ['spend', 'cost', 'tokens', 'usage', 'budget', 'price', 'estimate'],
    anchor: 'ai-spend',
  },
];
