/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResumesRouteImport } from './routes/resumes'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as AutopilotRouteImport } from './routes/autopilot'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AiGenerateRouteImport } from './routes/ai-generate'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesRoute = ResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotRoute = AutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGenerateRoute = AiGenerateRouteImport.update({
  id: '/ai-generate',
  path: '/ai-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-generate': typeof AiGenerateRoute
  '/analyze': typeof AnalyzeRoute
  '/autopilot': typeof AutopilotRoute
  '/jobs': typeof JobsRoute
  '/monitoring': typeof MonitoringRoute
  '/resumes': typeof ResumesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-generate': typeof AiGenerateRoute
  '/analyze': typeof AnalyzeRoute
  '/autopilot': typeof AutopilotRoute
  '/jobs': typeof JobsRoute
  '/monitoring': typeof MonitoringRoute
  '/resumes': typeof ResumesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-generate': typeof AiGenerateRoute
  '/analyze': typeof AnalyzeRoute
  '/autopilot': typeof AutopilotRoute
  '/jobs': typeof JobsRoute
  '/monitoring': typeof MonitoringRoute
  '/resumes': typeof ResumesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ai-generate'
    | '/analyze'
    | '/autopilot'
    | '/jobs'
    | '/monitoring'
    | '/resumes'
    | '/search'
    | '/settings'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/ai-generate'
    | '/analyze'
    | '/autopilot'
    | '/jobs'
    | '/monitoring'
    | '/resumes'
    | '/search'
    | '/settings'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ai-generate'
    | '/analyze'
    | '/autopilot'
    | '/jobs'
    | '/monitoring'
    | '/resumes'
    | '/search'
    | '/settings'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AiGenerateRoute: typeof AiGenerateRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AutopilotRoute: typeof AutopilotRoute
  JobsRoute: typeof JobsRoute
  MonitoringRoute: typeof MonitoringRoute
  ResumesRoute: typeof ResumesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes': {
      id: '/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot': {
      id: '/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-generate': {
      id: '/ai-generate'
      path: '/ai-generate'
      fullPath: '/ai-generate'
      preLoaderRoute: typeof AiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AiGenerateRoute: AiGenerateRoute,
  AnalyzeRoute: AnalyzeRoute,
  AutopilotRoute: AutopilotRoute,
  JobsRoute: JobsRoute,
  MonitoringRoute: MonitoringRoute,
  ResumesRoute: ResumesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
