/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexIndexRouteImport } from './routes/index/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes/index'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as AutopilotIndexRouteImport } from './routes/autopilot/index'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze/index'
import { Route as AiIndexRouteImport } from './routes/ai/index'
import { Route as AiGenerateIndexRouteImport } from './routes/ai-generate/index'

const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopilotIndexRoute = AutopilotIndexRouteImport.update({
  id: '/autopilot/',
  path: '/autopilot/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGenerateIndexRoute = AiGenerateIndexRouteImport.update({
  id: '/ai-generate/',
  path: '/ai-generate/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ai-generate/': typeof AiGenerateIndexRoute
  '/ai/': typeof AiIndexRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/autopilot/': typeof AutopilotIndexRoute
  '/index/': typeof IndexIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/ai-generate': typeof AiGenerateIndexRoute
  '/ai': typeof AiIndexRoute
  '/analyze': typeof AnalyzeIndexRoute
  '/autopilot': typeof AutopilotIndexRoute
  '/index': typeof IndexIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ai-generate/': typeof AiGenerateIndexRoute
  '/ai/': typeof AiIndexRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/autopilot/': typeof AutopilotIndexRoute
  '/index/': typeof IndexIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ai-generate/'
    | '/ai/'
    | '/analyze/'
    | '/autopilot/'
    | '/index/'
    | '/jobs/'
    | '/monitoring/'
    | '/resumes/'
    | '/search/'
    | '/settings/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-generate'
    | '/ai'
    | '/analyze'
    | '/autopilot'
    | '/index'
    | '/jobs'
    | '/monitoring'
    | '/resumes'
    | '/search'
    | '/settings'
    | '/support'
  id:
    | '__root__'
    | '/ai-generate/'
    | '/ai/'
    | '/analyze/'
    | '/autopilot/'
    | '/index/'
    | '/jobs/'
    | '/monitoring/'
    | '/resumes/'
    | '/search/'
    | '/settings/'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AiGenerateIndexRoute: typeof AiGenerateIndexRoute
  AiIndexRoute: typeof AiIndexRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
  AutopilotIndexRoute: typeof AutopilotIndexRoute
  IndexIndexRoute: typeof IndexIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopilot/': {
      id: '/autopilot/'
      path: '/autopilot'
      fullPath: '/autopilot/'
      preLoaderRoute: typeof AutopilotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-generate/': {
      id: '/ai-generate/'
      path: '/ai-generate'
      fullPath: '/ai-generate/'
      preLoaderRoute: typeof AiGenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AiGenerateIndexRoute: AiGenerateIndexRoute,
  AiIndexRoute: AiIndexRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
  AutopilotIndexRoute: AutopilotIndexRoute,
  IndexIndexRoute: IndexIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
