export function snakeCase(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

/** The banner every generated constants module opens with (`source` = its source of truth). */
export const generatedHeader = (source: string): string[] => [
  '// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.',
  `// Source of truth: ${source}`,
  '#![allow(dead_code)]',
  '',
];

/** rustfmt `max_width` — the column no emitted line may exceed. */
const RUST_MAX_WIDTH = 100;
/** rustfmt `array_width` under the default `use_small_heuristics`: the widest an
 *  array literal's CONTENT (items + their `, ` separators, brackets excluded)
 *  may be before the literal is laid out as a block. */
const RUST_ARRAY_WIDTH = 60;

/**
 * Emit `pub const <name>: <ty> = &[…];` in the form rustfmt already agrees with,
 * for ANY number of items — so a generated file stays `cargo fmt --check`-clean
 * and `pnpm gen:ipc:check`-stable however large a vocabulary grows.
 *
 * Verified against stable rustfmt 1.9, which decides in two independent steps:
 *
 * 1. the literal stays HORIZONTAL only while its content fits
 *    {@link RUST_ARRAY_WIDTH} — this is the step the previous per-generator
 *    heuristics missed, and it bites BEFORE {@link RUST_MAX_WIDTH} does;
 * 2. a horizontal literal whose declaration line would exceed
 *    {@link RUST_MAX_WIDTH} moves to its own 4-space-indented line (which always
 *    fits, being at most `RUST_ARRAY_WIDTH + 8` columns).
 *
 * Past `array_width` the literal becomes a BLOCK whose internal layout depends
 * on the widest element (`short_array_element_width_threshold`): rustfmt PACKS
 * short elements several per line and splits longer ones one per line. Rather
 * than re-derive that packing — the guess this helper exists to stop making —
 * the block form is emitted one element per line under `#[rustfmt::skip]`,
 * which rustfmt reproduces verbatim. A one-per-line block WITHOUT the attribute
 * would be repacked and fail `cargo fmt --check`.
 */
export function constSliceDecl(name: string, ty: string, items: string[]): string {
  const inline = items.join(', ');
  if (inline.length <= RUST_ARRAY_WIDTH) {
    const singleLine = `pub const ${name}: ${ty} = &[${inline}];`;
    return singleLine.length <= RUST_MAX_WIDTH
      ? singleLine
      : `pub const ${name}: ${ty} =\n    &[${inline}];`;
  }
  return [
    '#[rustfmt::skip]',
    `pub const ${name}: ${ty} = &[`,
    ...items.map((item) => `    ${item},`),
    '];',
  ].join('\n');
}

/** `pub const <name>: &[&str] = &[…];` for a TS string vocabulary, via {@link constSliceDecl}. */
export const strSliceDecl = (name: string, items: readonly string[]): string =>
  constSliceDecl(
    name,
    '&[&str]',
    items.map((item) => JSON.stringify(item))
  );
