/**
 * Prompt -> Rust content-validator lexicon codegen.
 *
 * The content validator's `voice.ai_tell_lexical` / `voice.ai_tell_prose` /
 * `voice.template_opener` checks
 * (`apps/desktop/src-tauri/src/validate/content/lexicon.rs`) must ban exactly
 * what the generation prompt's natural-voice ruleset
 * (`packages/prompts/src/generate/natural-voice/natural-voice.ts`) instructs
 * the model to avoid — a validator checking a different list than the prompt
 * used is a false-positive machine. This generates the Rust lexicon module
 * directly from natural-voice.ts's own exported word-list arrays, so the two
 * can never drift.
 *
 * Run `pnpm gen:prompts` to regenerate, or `pnpm gen:prompts:check` to fail
 * when the committed output is stale (used in CI). Mirrors
 * `packages/shared/scripts/gen-ipc-rust.ts`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  AI_TELL_LEXICAL_WORDS_DE,
  AI_TELL_LEXICAL_WORDS_EN,
  AI_TELL_PROSE_WORDS_DE,
  AI_TELL_PROSE_WORDS_EN,
  TEMPLATE_OPENERS_DE,
  TEMPLATE_OPENERS_EN,
} from '../src/generate/natural-voice/natural-voice.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const OUT_FILE = 'apps/desktop/src-tauri/src/validate/content/lexicon.rs';

/**
 * One `&[&str]` const, formatted to match `cargo fmt`'s own choice: a single
 * line when the whole declaration fits within rustfmt's 100-col `max_width`,
 * else one entry per line (rustfmt's vertical list layout for the arrays this
 * module emits — words/short phrases, never short enough on average to
 * trigger rustfmt's separate horizontal-packing tactic). `cargo fmt --check`
 * (CI) is the backstop if a future word list ever lands outside that shape.
 */
function rustArray(name: string, entries: readonly string[]): string {
  const items = entries.map((e) => JSON.stringify(e));
  const singleLine = `const ${name}: &[&str] = &[${items.join(', ')}];`;
  if (singleLine.length <= 100) return singleLine;
  return `const ${name}: &[&str] = &[\n${items.map((e) => `    ${e},`).join('\n')}\n];`;
}

/** `pub fn <name>(lang: &str) -> &'static [&'static str]` with de/en-fallback dispatch. */
function rustLookupFn(fnName: string, doc: string, enConst: string, deConst: string): string {
  return `${doc}
pub fn ${fnName}(lang: &str) -> &'static [&'static str] {
    match lang {
        "de" => ${deConst},
        _ => ${enConst},
    }
}`;
}

function generate(): string {
  const body = [
    rustLookupFn(
      'ai_tell_lexical',
      '/// Word/phrase bans safe inside a résumé bullet — the lexical tier of\n' +
        '/// `antiAiTellLexical()`. No prose-flow rules here.',
      'AI_TELL_LEXICAL_EN',
      'AI_TELL_LEXICAL_DE'
    ),
    rustLookupFn(
      'ai_tell_prose',
      '/// Prose-only patterns from `antiAiTellProse()` — negative parallelisms,\n' +
        '/// "-ing" depth-faking, and hedging preambles. Only meaningful for connected\n' +
        '/// writing (cover letters, summaries), never for a bullet.',
      'AI_TELL_PROSE_EN',
      'AI_TELL_PROSE_DE'
    ),
    rustLookupFn(
      'template_openers',
      '/// Stock cover-letter openers — the phrases a letter that could have been\n' +
        '/// addressed to anyone starts with.',
      'TEMPLATE_OPENERS_EN',
      'TEMPLATE_OPENERS_DE'
    ),
    rustArray('AI_TELL_LEXICAL_EN', AI_TELL_LEXICAL_WORDS_EN),
    rustArray('AI_TELL_LEXICAL_DE', AI_TELL_LEXICAL_WORDS_DE),
    rustArray('AI_TELL_PROSE_EN', AI_TELL_PROSE_WORDS_EN),
    rustArray('AI_TELL_PROSE_DE', AI_TELL_PROSE_WORDS_DE),
    rustArray('TEMPLATE_OPENERS_EN', TEMPLATE_OPENERS_EN),
    rustArray('TEMPLATE_OPENERS_DE', TEMPLATE_OPENERS_DE),
  ].join('\n\n');

  return [
    '// @generated by pnpm gen:prompts — DO NOT EDIT BY HAND.',
    '//',
    '//! Anti-AI-tell vocabulary, mirrored from the prompt side.',
    '//!',
    '//! Source of truth: `packages/prompts/src/generate/natural-voice/natural-voice.ts`',
    '//! (the `AI_TELL_LEXICAL_WORDS_*` / `AI_TELL_PROSE_WORDS_*` / `TEMPLATE_OPENERS_*`',
    '//! arrays) — the same bans the generation prompt hands the model, so the',
    '//! validator checks exactly what the prompt asked for. Run `pnpm gen:prompts`',
    '//! to regenerate after editing those arrays.',
    '//!',
    '//! `lang` is an ISO-639-1 code (`"en"`, `"de"`); anything else falls back to',
    '//! English, matching `normalizeLanguageCode` on the TS side. Entries are',
    '//! lowercase and matched with word boundaries (see `super::contains_phrase`),',
    '//! so `vital` never fires on `revitalize`.',
    '',
    body,
    '',
  ].join('\n');
}

const check = process.argv.includes('--check');
const target = join(REPO_ROOT, OUT_FILE);
const next = generate();

if (check) {
  let current: string;
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    current = '';
  }
  if (current !== next) {
    console.error(`✗ stale: ${OUT_FILE} — run \`pnpm gen:prompts\``);
    process.exit(1);
  }
  console.log('✓ prompts codegen output is up to date');
} else {
  writeFileSync(target, next);
  console.log(`✓ wrote ${OUT_FILE}`);
}
