/**
 * Prompt -> Rust codegen. Emits two generated files:
 *
 * - `apps/desktop/src-tauri/src/validate/content/lexicon.rs` — the content
 *   validator's `voice.ai_tell_lexical` and `voice.template_opener` checks
 *   (there is no separate prose CODE: `voice.rs::ai_tell_issues` merges the
 *   lexical and the prose array and reports both under `voice.ai_tell_lexical`)
 *   — must ban exactly what the generation prompt's natural-voice ruleset
 *   (`packages/prompts/src/generate/natural-voice/natural-voice.ts`) instructs
 *   the model to avoid — a validator checking a different list than the prompt
 *   used is a false-positive machine. Generated directly from
 *   natural-voice.ts's own exported word-list arrays, so the two can never
 *   drift.
 * - `apps/desktop/src-tauri/src/pipeline/resume/prompt_blocks.rs` — the pure
 *   prompt-side rule blocks (grounding rules, ATS precedence, humanize
 *   lexical, résumé conventions) the Rust résumé pipeline composes into its
 *   own stage prompts, generated by CALLING the same TS exports the
 *   renderer-driven prompts use, so a Rust stage prompt and its TS
 *   counterpart can never quietly drift into two paraphrases.
 *
 * Run `pnpm gen:prompts` to regenerate both, or `pnpm gen:prompts:check` to
 * fail when either committed output is stale (used in CI). Mirrors
 * `packages/shared/scripts/gen-ipc-rust.ts`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { FACTUAL_GROUNDING_RULES } from '../src/generate/emphasis/emphasis.js';
import {
  AI_TELL_LEXICAL_WORDS_DE,
  AI_TELL_LEXICAL_WORDS_EN,
  AI_TELL_LEXICAL_WORDS_IT,
  AI_TELL_PROSE_WORDS_DE,
  AI_TELL_PROSE_WORDS_EN,
  AI_TELL_PROSE_WORDS_IT,
  antiAiTellLexical,
  antiAiTellProse,
  HUMANIZE_LEXICAL,
  HUMANIZE_PROSE,
  TEMPLATE_OPENERS_DE,
  TEMPLATE_OPENERS_EN,
  TEMPLATE_OPENERS_IT,
} from '../src/generate/natural-voice/natural-voice.js';
import { ATS_PRECEDENCE } from '../src/generate/resume/resume.js';
import { rustResumeConventions } from './gen-prompts-rust/resume-conventions.js';
import { rustArray, rustLookupFn, rustStrConst } from './gen-prompts-rust/rust-emit.js';

export {
  hasRustUnsafeChar,
  rustArray,
  rustLookupFn,
  rustStrConst,
  rustStringLiteral,
} from './gen-prompts-rust/rust-emit.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const OUT_FILE = 'apps/desktop/src-tauri/src/validate/content/lexicon.rs';
const BLOCKS_OUT_FILE = 'apps/desktop/src-tauri/src/pipeline/resume/prompt_blocks.rs';

function generate(): string {
  const body = [
    rustLookupFn(
      'ai_tell_lexical',
      '/// Word/phrase bans safe inside a résumé bullet — the lexical tier of\n' +
        '/// `antiAiTellLexical()`. No prose-flow rules here.',
      'AI_TELL_LEXICAL_EN',
      'AI_TELL_LEXICAL_DE',
      'AI_TELL_LEXICAL_IT'
    ),
    rustLookupFn(
      'ai_tell_prose',
      '/// Prose-only patterns from `antiAiTellProse()` — the hedging preambles and\n' +
        '/// stock transitions it bans as PHRASES, wherever they appear. Only meaningful\n' +
        '/// for connected writing (cover letters, summaries), never for a bullet.\n' +
        '///\n' +
        "/// The prompt's CONSTRUCTION-dependent prose rules (negative parallelism,\n" +
        '/// superficial "-ing" openers/tails) are deliberately absent: a substring\n' +
        '/// check cannot tell the banned construction from an ordinary sentence that\n' +
        '/// happens to contain the same words, so it would flag prose the prompt\n' +
        "/// permits. They stay prompt-only — see `AI_TELL_PROSE_WORDS_EN`'s doc in\n" +
        '/// natural-voice.ts.',
      'AI_TELL_PROSE_EN',
      'AI_TELL_PROSE_DE',
      'AI_TELL_PROSE_IT'
    ),
    rustLookupFn(
      'template_openers',
      '/// Stock cover-letter openers — the phrases a letter that could have been\n' +
        '/// addressed to anyone starts with.',
      'TEMPLATE_OPENERS_EN',
      'TEMPLATE_OPENERS_DE',
      'TEMPLATE_OPENERS_IT'
    ),
    rustArray('AI_TELL_LEXICAL_EN', AI_TELL_LEXICAL_WORDS_EN),
    rustArray('AI_TELL_LEXICAL_DE', AI_TELL_LEXICAL_WORDS_DE),
    rustArray('AI_TELL_LEXICAL_IT', AI_TELL_LEXICAL_WORDS_IT),
    rustArray('AI_TELL_PROSE_EN', AI_TELL_PROSE_WORDS_EN),
    rustArray('AI_TELL_PROSE_DE', AI_TELL_PROSE_WORDS_DE),
    rustArray('AI_TELL_PROSE_IT', AI_TELL_PROSE_WORDS_IT),
    rustArray('TEMPLATE_OPENERS_EN', TEMPLATE_OPENERS_EN),
    rustArray('TEMPLATE_OPENERS_DE', TEMPLATE_OPENERS_DE),
    rustArray('TEMPLATE_OPENERS_IT', TEMPLATE_OPENERS_IT),
  ].join('\n\n');

  return [
    '// @generated by pnpm gen:prompts — DO NOT EDIT BY HAND.',
    '//',
    '//! Anti-AI-tell vocabulary, mirrored from the prompt side.',
    '//!',
    '//! Source of truth: `packages/prompts/src/generate/natural-voice/natural-voice.ts`',
    '//! (the `AI_TELL_LEXICAL_WORDS_*` / `AI_TELL_PROSE_WORDS_*` / `TEMPLATE_OPENERS_*`',
    '//! arrays) — the same bans the generation prompt hands the model, so the',
    '//! validator checks exactly what the prompt asked for. Run `pnpm gen:prompts`',
    '//! to regenerate after editing those arrays.',
    '//!',
    '//! `lang` is an ISO-639-1 code. `"en"`/`"de"`/`"it"` return their curated lists;',
    '//! every OTHER language returns an EMPTY slice, never the English list —',
    '//! `natural-voice.ts` sends an uncurated language a generic, wordless',
    '//! directive instead (see its `genericAntiAiTellLexical`/',
    '//! `genericAntiAiTellProse`), so falling back to English words here would',
    '//! flag a language the prompt never told to avoid them. Entries are',
    '//! lowercase and matched with word boundaries (see `super::contains_phrase`),',
    '//! so `vital` never fires on `revitalize`.',
    '',
    body,
    '',
  ].join('\n');
}

/**
 * The stage-block module: the pure, prompt-side rule blocks the Rust résumé
 * pipeline composes into its own stage prompts. Frozen from the SAME TS values
 * the renderer-driven prompts use, so the backend can never quietly drift into
 * a paraphrase.
 */
function generateBlocks(): string {
  const body = [
    rustStrConst(
      '/// The résumé is the ONLY source of claims about the candidate; the job ad\n' +
        '/// is a target, never evidence. Shared verbatim with the cover-letter,\n' +
        '/// application-email, and application-questions prompts.',
      'FACTUAL_GROUNDING_RULES',
      FACTUAL_GROUNDING_RULES
    ),
    rustStrConst(
      '/// ATS keyword match outranks the anti-AI-tell word bans: an exact job-ad\n' +
        '/// term the résumé truthfully supports is kept even when it is on the\n' +
        '/// discouraged list. The bans govern only words the model introduces itself.',
      'ATS_PRECEDENCE',
      ATS_PRECEDENCE
    ),
    rustStrConst(
      '/// The POSITIVE résumé-tier voice block — specificity and bullet variety —\n' +
        '/// composed ALONGSIDE the anti-AI-tell bans, never instead of them. Résumé\n' +
        '/// tier stays ATS-safe (no contractions, no fragments).',
      'HUMANIZE_LEXICAL',
      HUMANIZE_LEXICAL
    ),
    rustStrConst(
      '/// The lexical-tier anti-AI-tell BAN LIST (English, full depth) — word/phrase\n' +
        '/// bans safe inside a résumé bullet. `draft`/`repair` compose only\n' +
        "/// `HUMANIZE_LEXICAL` (the positive block); the `humanize` stage's résumé\n" +
        '/// tier composes this PLUS `HUMANIZE_LEXICAL`, mirroring\n' +
        "/// `packages/prompts/src/generate/rewrite/rewrite.ts`'s `buildDocVoice`,\n" +
        "/// which is the app's existing single-span rewrite prompt for the same two\n" +
        '/// tiers. English only, like every other block on this page: Rust prompts\n' +
        '/// steer the OUTPUT language via `system_language`; the RULE text itself\n' +
        '/// stays English, the same choice `HUMANIZE_LEXICAL` already made.',
      'ANTI_AI_TELL_LEXICAL',
      antiAiTellLexical('en')
    ),
    rustStrConst(
      '/// The prose-tier anti-AI-tell ruleset (English, full depth): the lexical\n' +
        '/// bans plus prose-flow rules (em dash, rhythm, rule-of-three, template\n' +
        '/// openers). Composed with `HUMANIZE_PROSE` for the letter/prose voice —\n' +
        "/// the `cover_letter` stage and `humanize`'s letter tier.",
      'ANTI_AI_TELL_PROSE',
      antiAiTellProse('en')
    ),
    rustStrConst(
      '/// The POSITIVE prose-tier voice block — cadence, concreteness, controlled\n' +
        '/// imperfection — composed ALONGSIDE `ANTI_AI_TELL_PROSE`, never instead of\n' +
        '/// it. Prose tier (letters, not résumé bullets).',
      'HUMANIZE_PROSE',
      HUMANIZE_PROSE
    ),
    rustResumeConventions(),
  ].join('\n\n');

  return [
    '// @generated by pnpm gen:prompts — DO NOT EDIT BY HAND.',
    '//',
    '//! Pure prompt BLOCKS shared with the TypeScript prompt builders.',
    '//!',
    '//! Source of truth: `packages/prompts` — `generate/emphasis`',
    '//! (`FACTUAL_GROUNDING_RULES`), `generate/resume` (`ATS_PRECEDENCE`),',
    '//! `generate/natural-voice` (`HUMANIZE_LEXICAL`), and `locale`',
    '//! (`resumeConventions`). Generated by CALLING those exports, so a Rust stage',
    '//! prompt and the renderer-driven prompt for the same job state the identical',
    '//! rule instead of two paraphrases that drift.',
    '//!',
    '//! Run `pnpm gen:prompts` to regenerate after editing them; `pnpm',
    '//! gen:prompts:check` fails the build when this file is stale.',
    '#![allow(dead_code)]',
    '',
    body,
    '',
  ].join('\n');
}

function main(): void {
  const check = process.argv.includes('--check');
  const outputs: { outFile: string; content: string }[] = [
    { outFile: OUT_FILE, content: generate() },
    { outFile: BLOCKS_OUT_FILE, content: generateBlocks() },
  ];

  let stale = false;
  for (const { outFile, content: next } of outputs) {
    const target = join(REPO_ROOT, outFile);
    if (check) {
      let current: string;
      try {
        current = readFileSync(target, 'utf8');
      } catch {
        current = '';
      }
      if (current !== next) {
        stale = true;
        console.error(`✗ stale: ${outFile} — run \`pnpm gen:prompts\``);
      }
    } else {
      mkdirSync(dirname(join(REPO_ROOT, outFile)), { recursive: true });
      writeFileSync(target, next);
      console.log(`✓ wrote ${outFile}`);
    }
  }

  if (check && stale) process.exit(1);
  if (check) console.log('✓ prompts codegen output is up to date');
}

// Only run when executed directly (`tsx scripts/gen-prompts-rust.ts`), not when
// imported by a test for its pure helpers (`hasRustUnsafeChar`/`rustArray`) — a
// bare top-level call would otherwise overwrite `lexicon.rs` as a side effect
// of running the test suite.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
