// @generated by pnpm gen:prompts — DO NOT EDIT BY HAND.
//
//! Anti-AI-tell vocabulary, mirrored from the prompt side.
//!
//! Source of truth: `packages/prompts/src/generate/natural-voice/natural-voice.ts`
//! (the `AI_TELL_LEXICAL_WORDS_*` / `AI_TELL_PROSE_WORDS_*` / `TEMPLATE_OPENERS_*`
//! arrays) — the same bans the generation prompt hands the model, so the
//! validator checks exactly what the prompt asked for. Run `pnpm gen:prompts`
//! to regenerate after editing those arrays.
//!
//! `lang` is an ISO-639-1 code. `"en"`/`"de"` return their curated lists;
//! every OTHER language returns an EMPTY slice, never the English list —
//! `natural-voice.ts` sends an uncurated language a generic, wordless
//! directive instead (see its `genericAntiAiTellLexical`/
//! `genericAntiAiTellProse`), so falling back to English words here would
//! flag a language the prompt never told to avoid them. Entries are
//! lowercase and matched with word boundaries (see `super::contains_phrase`),
//! so `vital` never fires on `revitalize`.

/// Word/phrase bans safe inside a résumé bullet — the lexical tier of
/// `antiAiTellLexical()`. No prose-flow rules here.
pub fn ai_tell_lexical(lang: &str) -> &'static [&'static str] {
    match lang {
        "de" => AI_TELL_LEXICAL_DE,
        "en" => AI_TELL_LEXICAL_EN,
        // Every other language gets the prompt's generic, wordless directive
        // (see natural-voice.ts's genericAntiAiTellLexical/Prose) — there is
        // no curated list to check it against.
        _ => &[],
    }
}

/// Prose-only patterns from `antiAiTellProse()` — the hedging preambles and
/// stock transitions it bans as PHRASES, wherever they appear. Only meaningful
/// for connected writing (cover letters, summaries), never for a bullet.
///
/// The prompt's CONSTRUCTION-dependent prose rules (negative parallelism,
/// superficial "-ing" openers/tails) are deliberately absent: a substring
/// check cannot tell the banned construction from an ordinary sentence that
/// happens to contain the same words, so it would flag prose the prompt
/// permits. They stay prompt-only — see `AI_TELL_PROSE_WORDS_EN`'s doc in
/// natural-voice.ts.
pub fn ai_tell_prose(lang: &str) -> &'static [&'static str] {
    match lang {
        "de" => AI_TELL_PROSE_DE,
        "en" => AI_TELL_PROSE_EN,
        // Every other language gets the prompt's generic, wordless directive
        // (see natural-voice.ts's genericAntiAiTellLexical/Prose) — there is
        // no curated list to check it against.
        _ => &[],
    }
}

/// Stock cover-letter openers — the phrases a letter that could have been
/// addressed to anyone starts with.
pub fn template_openers(lang: &str) -> &'static [&'static str] {
    match lang {
        "de" => TEMPLATE_OPENERS_DE,
        "en" => TEMPLATE_OPENERS_EN,
        // Every other language gets the prompt's generic, wordless directive
        // (see natural-voice.ts's genericAntiAiTellLexical/Prose) — there is
        // no curated list to check it against.
        _ => &[],
    }
}

const AI_TELL_LEXICAL_EN: &[&str] = &[
    "delve",
    "leverage",
    "robust",
    "seamless",
    "cutting-edge",
    "tapestry",
    "testament",
    "realm",
    "underscore",
    "showcase",
    "foster",
    "intricate",
    "pivotal",
    "vibrant",
    "garner",
    "vital",
    "crucial",
    "harness",
    "elevate",
    "streamline",
    "unlock",
    "empower",
    "passionate",
    "results-driven",
    "proven track record",
    "team player",
    "go-getter",
    "synergy",
    "detail-oriented",
    "world-class",
    "studies show",
    "experts say",
    "industry reports",
    "it is widely known",
    "in order to",
    "due to the fact that",
    "at this point in time",
    "has the ability to",
];

const AI_TELL_LEXICAL_DE: &[&str] = &[
    "darüber hinaus",
    "nahtlos",
    "robust",
    "spielt eine entscheidende rolle",
    "in der heutigen zeit",
    "in der heutigen welt",
    "in einem dynamischen umfeld",
    "mit großer begeisterung",
    "leidenschaft für",
    "eine spannende herausforderung",
    "maßgeschneidert",
    "eintauchen in",
    "ergebnisorientiert",
    "teamplayer",
    "nachgewiesene erfolgsbilanz",
    "detailorientiert",
    "weltklasse",
    "studien zeigen",
    "experten sagen",
    "es ist allgemein bekannt",
];

const AI_TELL_PROSE_EN: &[&str] = &[
    "it is important to note",
    "generally speaking",
    "with that in mind",
    "building on this",
];

const AI_TELL_PROSE_DE: &[&str] = &[];

const TEMPLATE_OPENERS_EN: &[&str] = &[
    "i am writing to apply",
    "i am writing to express",
    "i am writing in response to",
    "i am excited to apply",
    "i would like to apply for the position",
    "please accept this letter",
    "with great interest i read",
    "i hope this message finds you well",
    "i hope this email finds you well",
    "as a passionate",
];

const TEMPLATE_OPENERS_DE: &[&str] = &[
    "hiermit bewerbe ich mich",
    "hiermit möchte ich mich bewerben",
    "mit großem interesse habe ich ihre stellenanzeige",
    "mit großem interesse habe ich gelesen",
    "auf ihre stellenanzeige hin",
    "wie ihrer stellenanzeige zu entnehmen ist",
];
