export const COMMON_TECH: { name: string; category: string }[] = [
  // language
  { name: 'JavaScript', category: 'language' },
  { name: 'TypeScript', category: 'language' },
  { name: 'Python', category: 'language' },
  { name: 'Go', category: 'language' },
  { name: 'Rust', category: 'language' },
  { name: 'Java', category: 'language' },
  { name: 'Kotlin', category: 'language' },
  { name: 'Swift', category: 'language' },
  { name: 'C#', category: 'language' },
  { name: 'C++', category: 'language' },
  { name: 'C', category: 'language' },
  { name: 'Ruby', category: 'language' },
  { name: 'PHP', category: 'language' },
  { name: 'Scala', category: 'language' },
  { name: 'Elixir', category: 'language' },
  { name: 'Dart', category: 'language' },
  { name: 'R', category: 'language' },
  { name: 'Perl', category: 'language' },
  { name: 'Haskell', category: 'language' },
  { name: 'Clojure', category: 'language' },
  { name: 'Lua', category: 'language' },
  { name: 'Objective-C', category: 'language' },
  { name: 'SQL', category: 'language' },
  { name: 'Bash', category: 'language' },
  { name: 'GraphQL', category: 'language' },
  { name: 'HTML', category: 'language' },
  { name: 'CSS', category: 'language' },
  { name: 'Sass', category: 'language' },
  { name: 'F#', category: 'language' },
  { name: 'Erlang', category: 'language' },
  { name: 'Groovy', category: 'language' },
  { name: 'Julia', category: 'language' },
  { name: 'MATLAB', category: 'language' },
  { name: 'Solidity', category: 'language' },
  { name: 'Zig', category: 'language' },
  { name: 'OCaml', category: 'language' },
  { name: 'Assembly', category: 'language' },
  { name: 'PowerShell', category: 'language' },
  { name: 'VB.NET', category: 'language' },
  { name: 'COBOL', category: 'language' },

  // framework
  { name: 'React', category: 'framework' },
  { name: 'Next.js', category: 'framework' },
  { name: 'Vue', category: 'framework' },
  { name: 'Nuxt', category: 'framework' },
  { name: 'Angular', category: 'framework' },
  { name: 'Svelte', category: 'framework' },
  { name: 'SvelteKit', category: 'framework' },
  { name: 'Solid', category: 'framework' },
  { name: 'Node.js', category: 'framework' },
  { name: 'Express', category: 'framework' },
  { name: 'NestJS', category: 'framework' },
  { name: 'Deno', category: 'framework' },
  { name: 'Bun', category: 'framework' },
  { name: 'Django', category: 'framework' },
  { name: 'Flask', category: 'framework' },
  { name: 'FastAPI', category: 'framework' },
  { name: 'Spring', category: 'framework' },
  { name: 'Spring Boot', category: 'framework' },
  { name: 'Rails', category: 'framework' },
  { name: 'Laravel', category: 'framework' },
  { name: '.NET', category: 'framework' },
  { name: 'ASP.NET', category: 'framework' },
  { name: 'Flutter', category: 'framework' },
  { name: 'React Native', category: 'framework' },
  { name: 'Electron', category: 'framework' },
  { name: 'Tauri', category: 'framework' },
  { name: 'Tailwind CSS', category: 'framework' },
  { name: 'Redux', category: 'framework' },
  { name: 'RxJS', category: 'framework' },
  { name: 'jQuery', category: 'framework' },
  { name: 'Symfony', category: 'framework' },
  { name: 'Phoenix', category: 'framework' },
  { name: 'Gin', category: 'framework' },
  { name: 'Actix', category: 'framework' },
  { name: 'Axum', category: 'framework' },
  { name: 'Remix', category: 'framework' },
  { name: 'Astro', category: 'framework' },
  { name: 'Ember', category: 'framework' },
  { name: 'Backbone', category: 'framework' },
  { name: 'Gatsby', category: 'framework' },
  { name: 'Qwik', category: 'framework' },
  { name: 'Bootstrap', category: 'framework' },
  { name: 'Material UI', category: 'framework' },
  { name: 'Chakra UI', category: 'framework' },
  { name: 'Zustand', category: 'framework' },
  { name: 'MobX', category: 'framework' },
  { name: 'Vuex', category: 'framework' },
  { name: 'Pinia', category: 'framework' },
  { name: 'Hibernate', category: 'framework' },
  { name: 'Quarkus', category: 'framework' },
  { name: 'Micronaut', category: 'framework' },
  { name: 'Ktor', category: 'framework' },
  { name: 'Vapor', category: 'framework' },
  { name: 'SwiftUI', category: 'framework' },
  { name: 'Jetpack Compose', category: 'framework' },
  { name: 'Xamarin', category: 'framework' },
  { name: 'Ionic', category: 'framework' },

  // database
  { name: 'PostgreSQL', category: 'database' },
  { name: 'MySQL', category: 'database' },
  { name: 'MariaDB', category: 'database' },
  { name: 'SQLite', category: 'database' },
  { name: 'MongoDB', category: 'database' },
  { name: 'Redis', category: 'database' },
  { name: 'Cassandra', category: 'database' },
  { name: 'DynamoDB', category: 'database' },
  { name: 'Elasticsearch', category: 'database' },
  { name: 'Neo4j', category: 'database' },
  { name: 'CockroachDB', category: 'database' },
  { name: 'Snowflake', category: 'database' },
  { name: 'BigQuery', category: 'database' },
  { name: 'Supabase', category: 'database' },
  { name: 'Firebase', category: 'database' },
  { name: 'Prisma', category: 'database' },
  { name: 'Oracle', category: 'database' },
  { name: 'SQL Server', category: 'database' },
  { name: 'Couchbase', category: 'database' },
  { name: 'InfluxDB', category: 'database' },
  { name: 'ClickHouse', category: 'database' },
  { name: 'Memcached', category: 'database' },
  { name: 'RethinkDB', category: 'database' },
  { name: 'FaunaDB', category: 'database' },
  { name: 'Drizzle', category: 'database' },
  { name: 'TypeORM', category: 'database' },
  { name: 'Sequelize', category: 'database' },
  { name: 'Mongoose', category: 'database' },

  // tool
  { name: 'Docker', category: 'tool' },
  { name: 'Kubernetes', category: 'tool' },
  { name: 'Git', category: 'tool' },
  { name: 'GitHub Actions', category: 'tool' },
  { name: 'GitLab CI', category: 'tool' },
  { name: 'Jenkins', category: 'tool' },
  { name: 'Terraform', category: 'tool' },
  { name: 'Ansible', category: 'tool' },
  { name: 'AWS', category: 'tool' },
  { name: 'GCP', category: 'tool' },
  { name: 'Azure', category: 'tool' },
  { name: 'Vercel', category: 'tool' },
  { name: 'Netlify', category: 'tool' },
  { name: 'Nginx', category: 'tool' },
  { name: 'Kafka', category: 'tool' },
  { name: 'RabbitMQ', category: 'tool' },
  { name: 'gRPC', category: 'tool' },
  { name: 'Webpack', category: 'tool' },
  { name: 'Vite', category: 'tool' },
  { name: 'ESBuild', category: 'tool' },
  { name: 'Babel', category: 'tool' },
  { name: 'Jest', category: 'tool' },
  { name: 'Vitest', category: 'tool' },
  { name: 'Playwright', category: 'tool' },
  { name: 'Cypress', category: 'tool' },
  { name: 'Storybook', category: 'tool' },
  { name: 'Figma', category: 'tool' },
  { name: 'Jira', category: 'tool' },
  { name: 'Linux', category: 'tool' },
  { name: 'Apache', category: 'tool' },
  { name: 'Helm', category: 'tool' },
  { name: 'Prometheus', category: 'tool' },
  { name: 'Grafana', category: 'tool' },
  { name: 'Datadog', category: 'tool' },
  { name: 'Sentry', category: 'tool' },
  { name: 'Pulumi', category: 'tool' },
  { name: 'CircleCI', category: 'tool' },
  { name: 'Travis CI', category: 'tool' },
  { name: 'Bitbucket', category: 'tool' },
  { name: 'Confluence', category: 'tool' },
  { name: 'Postman', category: 'tool' },
  { name: 'Swagger', category: 'tool' },
  { name: 'OpenAPI', category: 'tool' },
  { name: 'Selenium', category: 'tool' },
  { name: 'Puppeteer', category: 'tool' },
  { name: 'Testing Library', category: 'tool' },
  { name: 'ESLint', category: 'tool' },
  { name: 'Prettier', category: 'tool' },
  { name: 'Rollup', category: 'tool' },
  { name: 'Turbopack', category: 'tool' },
  { name: 'pnpm', category: 'tool' },
  { name: 'npm', category: 'tool' },
  { name: 'Yarn', category: 'tool' },
  { name: 'Bazel', category: 'tool' },
  { name: 'Make', category: 'tool' },
  { name: 'CMake', category: 'tool' },
  { name: 'Gradle', category: 'tool' },
  { name: 'Maven', category: 'tool' },
  { name: 'Consul', category: 'tool' },
  { name: 'Vault', category: 'tool' },
  { name: 'Istio', category: 'tool' },
  { name: 'Argo CD', category: 'tool' },
  { name: 'Spinnaker', category: 'tool' },
  { name: 'Cloudflare', category: 'tool' },
  { name: 'DigitalOcean', category: 'tool' },
  { name: 'Heroku', category: 'tool' },
  { name: 'Fastlane', category: 'tool' },
  { name: 'Xcode', category: 'tool' },
  { name: 'Android Studio', category: 'tool' },
  { name: 'IntelliJ IDEA', category: 'tool' },
  { name: 'VS Code', category: 'tool' },
  { name: 'Vim', category: 'tool' },
  { name: 'Neovim', category: 'tool' },
];
