// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AiGenerateRequest {
    pub model: String,
    pub messages: Vec<AiGenerateRequestMessage>,
    pub locale: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context_window: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AiGenerateRequestMessage {
    pub role: String,
    pub content: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AiEmbedRequest {
    pub text: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AiGenerationSaveRequest {
    #[serde(default = "default_ai_generation_save_request_candidate_name")]
    pub candidate_name: String,
    #[serde(default = "default_ai_generation_save_request_job_title")]
    pub job_title: String,
    #[serde(default = "default_ai_generation_save_request_company_name")]
    pub company_name: String,
    #[serde(default = "default_ai_generation_save_request_resume_language")]
    pub resume_language: String,
    #[serde(default = "default_ai_generation_save_request_job_ad_language")]
    pub job_ad_language: String,
    #[serde(default = "default_ai_generation_save_request_target_language")]
    pub target_language: String,
    #[serde(default = "default_ai_generation_save_request_mismatch")]
    pub mismatch: bool,
    #[serde(default = "default_ai_generation_save_request_top_requirements")]
    pub top_requirements: Vec<String>,
    #[serde(default = "default_ai_generation_save_request_mode")]
    pub mode: String,
    #[serde(default = "default_ai_generation_save_request_resume_text")]
    pub resume_text: String,
    #[serde(default = "default_ai_generation_save_request_cover_letter_text")]
    pub cover_letter_text: String,
    #[serde(default = "default_ai_generation_save_request_job_ad")]
    pub job_ad: String,
    #[serde(default = "default_ai_generation_save_request_job_url")]
    pub job_url: String,
    #[serde(default = "default_ai_generation_save_request_board")]
    pub board: String,
    #[serde(default = "default_ai_generation_save_request_application_answers")]
    pub application_answers: Vec<AiGenerationSaveRequestApplicationAnswer>,
    #[serde(default = "default_ai_generation_save_request_company_brief")]
    pub company_brief: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AiGenerationSaveRequestApplicationAnswer {
    #[serde(default = "default_ai_generation_save_request_application_answer_id")]
    pub id: String,
    #[serde(default = "default_ai_generation_save_request_application_answer_question")]
    pub question: String,
    #[serde(default = "default_ai_generation_save_request_application_answer_answer")]
    pub answer: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AiGenerationUpdateRequest {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resume_text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cover_letter_text: Option<String>,
}

fn default_ai_generation_save_request_candidate_name() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_job_title() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_company_name() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_resume_language() -> String {
    "en".to_string()
}

fn default_ai_generation_save_request_job_ad_language() -> String {
    "en".to_string()
}

fn default_ai_generation_save_request_target_language() -> String {
    "en".to_string()
}

fn default_ai_generation_save_request_mismatch() -> bool {
    false
}

fn default_ai_generation_save_request_top_requirements() -> Vec<String> {
    Vec::new()
}

fn default_ai_generation_save_request_mode() -> String {
    "ats".to_string()
}

fn default_ai_generation_save_request_resume_text() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_cover_letter_text() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_job_ad() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_job_url() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_board() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_application_answers(
) -> Vec<AiGenerationSaveRequestApplicationAnswer> {
    Vec::new()
}

fn default_ai_generation_save_request_company_brief() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_application_answer_id() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_application_answer_question() -> String {
    "".to_string()
}

fn default_ai_generation_save_request_application_answer_answer() -> String {
    "".to_string()
}
