// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct ApplyStartRequest {
    pub board: String,
    pub url: String,
    pub cover_letter: Option<String>,
    pub resume_path: Option<String>,
    pub auto_submit: Option<bool>,
}
