// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AutopilotCreateRequest {
    pub name: String,
    pub target: AutopilotCreateRequestTarget,
    pub filter: AutopilotCreateRequestFilter,
    pub schedule: String,
    pub schedule_hour: Option<u32>,
    pub schedule_minute: Option<u32>,
    pub resume_text: Option<String>,
    pub cover_letter: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AutopilotCreateRequestTarget {
    pub board: String,
    pub query: String,
    pub location: Option<String>,
    pub work_type: Option<String>,
    #[serde(default = "default_autopilot_create_request_target_pages")]
    pub pages: u32,
    pub date_filter: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AutopilotCreateRequestFilter {
    #[serde(default = "default_autopilot_create_request_filter_min_match_score")]
    pub min_match_score: f64,
    pub keywords: Option<Vec<String>>,
    pub exclude_keywords: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AutopilotUpdateRequest {
    pub name: Option<String>,
    pub target: Option<AutopilotUpdateRequestTarget>,
    pub filter: Option<AutopilotUpdateRequestFilter>,
    pub schedule: Option<String>,
    pub schedule_hour: Option<u32>,
    pub schedule_minute: Option<u32>,
    pub resume_text: Option<String>,
    pub cover_letter: Option<String>,
    pub status: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AutopilotUpdateRequestTarget {
    pub board: String,
    pub query: String,
    pub location: Option<String>,
    pub work_type: Option<String>,
    #[serde(default = "default_autopilot_update_request_target_pages")]
    pub pages: u32,
    pub date_filter: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AutopilotUpdateRequestFilter {
    #[serde(default = "default_autopilot_update_request_filter_min_match_score")]
    pub min_match_score: f64,
    pub keywords: Option<Vec<String>>,
    pub exclude_keywords: Option<Vec<String>>,
}

fn default_autopilot_create_request_target_pages() -> u32 {
    2
}

fn default_autopilot_create_request_filter_min_match_score() -> f64 {
    50.0
}

fn default_autopilot_update_request_target_pages() -> u32 {
    2
}

fn default_autopilot_update_request_filter_min_match_score() -> f64 {
    50.0
}
