// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct ConversationSaveMessageRequest {
    #[serde(default = "default_conversation_save_message_request_conversation_id")]
    pub conversation_id: String,
    #[serde(default = "default_conversation_save_message_request_role")]
    pub role: String,
    #[serde(default = "default_conversation_save_message_request_content")]
    pub content: String,
}

fn default_conversation_save_message_request_conversation_id() -> String {
    "default".to_string()
}

fn default_conversation_save_message_request_role() -> String {
    "user".to_string()
}

fn default_conversation_save_message_request_content() -> String {
    "".to_string()
}
