// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct DocumentsImportRequest {
    pub name: String,
    pub bytes: Vec<u8>,
    pub title: Option<String>,
    pub locale: Option<String>,
}
