// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/events/index.ts
#![allow(dead_code)]

pub const AI_STREAM: &str = "ai:stream";
pub const JOBS_EVENT: &str = "jobs:event";
pub const APPLICATIONS_CHANGED: &str = "applications:changed";
pub const NOTIFICATIONS_CHANGED: &str = "notifications:changed";
pub const NOTIFICATIONS_OPEN: &str = "notifications:open";
pub const NOTIFICATIONS_TOAST: &str = "notifications:toast";
pub const UPDATER_STATUS: &str = "updater:status";
pub const MENU_NAVIGATE: &str = "menu:navigate";
pub const MENU_ACTION: &str = "menu:action";
pub const AUTOPILOT_FOCUS: &str = "autopilot:focus";
pub const AUTOPILOT_STEP: &str = "autopilot:step";
pub const SCRAPE_PROGRESS: &str = "scrape:progress";
pub const SCRAPE_ITEM: &str = "scrape:item";
pub const BOARDS_LOGIN_STATUS: &str = "boards:login-status";
pub const SHORTCUT_COMMAND_PALETTE: &str = "shortcut:command-palette";
