// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
//
// Fields are (de)serialized across the Tauri IPC boundary and never read
// directly in Rust — the allow is intentional for generated serde DTOs.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MatchResumeRequest {
    pub resume_id: String,
    pub job_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub semantic_scoring_enabled: Option<bool>,
}
