// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct MatchResumeRequest {
    pub resume_id: String,
    pub job_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub semantic_scoring_enabled: Option<bool>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct MatchResumeBatchRequest {
    pub resume_id: String,
    pub job_ids: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub semantic_scoring_enabled: Option<bool>,
}
