// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct ReferralUpsertRequest {
    pub id: Option<String>,
    #[serde(default = "default_referral_upsert_request_job_url")]
    pub job_url: String,
    #[serde(default = "default_referral_upsert_request_company_name")]
    pub company_name: String,
    #[serde(default = "default_referral_upsert_request_person_name")]
    pub person_name: String,
    pub person_role: Option<String>,
    pub linkedin_url: Option<String>,
    pub email_draft: Option<String>,
    pub message_draft: Option<String>,
    pub invite_note_draft: Option<String>,
    #[serde(default = "default_referral_upsert_request_channel")]
    pub channel: String,
    #[serde(default = "default_referral_upsert_request_status")]
    pub status: String,
    pub notes: Option<String>,
}

fn default_referral_upsert_request_job_url() -> String {
    "".to_string()
}

fn default_referral_upsert_request_company_name() -> String {
    "".to_string()
}

fn default_referral_upsert_request_person_name() -> String {
    "".to_string()
}

fn default_referral_upsert_request_channel() -> String {
    "email".to_string()
}

fn default_referral_upsert_request_status() -> String {
    "draft".to_string()
}
