// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
//
// Fields are (de)serialized across the Tauri IPC boundary and never read
// directly in Rust — the allow is intentional for generated serde DTOs.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ReferralUpsertRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default = "default_referral_upsert_request_job_url")]
    pub job_url: String,
    #[serde(default = "default_referral_upsert_request_company_name")]
    pub company_name: String,
    #[serde(default = "default_referral_upsert_request_person_name")]
    pub person_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub person_role: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub linkedin_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_draft: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_draft: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invite_note_draft: Option<String>,
    #[serde(default = "default_referral_upsert_request_channel")]
    pub channel: String,
    #[serde(default = "default_referral_upsert_request_status")]
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

fn default_referral_upsert_request_job_url() -> String {
    "".to_string()
}

fn default_referral_upsert_request_company_name() -> String {
    "".to_string()
}

fn default_referral_upsert_request_person_name() -> String {
    "".to_string()
}

fn default_referral_upsert_request_channel() -> String {
    "email".to_string()
}

fn default_referral_upsert_request_status() -> String {
    "draft".to_string()
}
