// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
//
// Fields are (de)serialized across the Tauri IPC boundary and never read
// directly in Rust — the allow is intentional for generated serde DTOs.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ResumeExtractTextRequest {
    pub name: String,
    pub bytes: Vec<u8>,
}
