// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct HybridSearchRequest {
    pub query: String,
    pub collection: String,
    #[serde(default = "default_hybrid_search_request_top_k")]
    pub top_k: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filters: Option<serde_json::Value>,
    #[serde(default = "default_hybrid_search_request_semantic_weight")]
    pub semantic_weight: f64,
}

fn default_hybrid_search_request_top_k() -> u32 {
    20
}

fn default_hybrid_search_request_semantic_weight() -> f64 {
    0.7
}
