// All human-visible copy for BEAT 2 (the descent). ASCII-only, \uXXXX-escaped.
export const beat2 = {
  h2: "the descent",
  doodleAria: "poke the frazzled guy",
  doodleVoice: "frazzled",
  doodleLines: "WHY won't they reply|i can't keep up|so many tabs|make it STOP|aaaaaa",
  chips: ["LinkedIn", "Indeed", "Glassdoor", "StepStone", "Xing", "Greenhouse", "Lever", "Workday"],
  chipsMore: "+15 more",
  tagA: "entry level: 5 yrs experience required \u00B7 easy apply (47 fields) \u00B7 create a Workday account ",
  tagItalic: "(for the 9th time)",
  blackholeYell: "HELLO??",
  blackholeMain: "\"thank you for your interest, we'll be in touch.\"",
  blackholeEcho: "(they will not be in touch)",
  blackholeStatus: "\u2191 application status",
  atsTitle: "the r\u00E9sum\u00E9 robot",
  atsBold: "BEEP. REJECTED.",
  atsSub: "a human will never see this.",
  recruitersTitle: "recruiters (every one of them)",
  npcs: ["\"on file\"", "\"more senior\"", "\"more junior\"", "\"someone\""],
  linkedinTitle: "meanwhile, on LinkedIn",
  feed: [
    "\uD83C\uDF89 thrilled to announce",
    "humbled and honored",
    "after 47 rounds of interviews, delighted to share\u2026",
    "so grateful for this journey",
  ],
  linkedinGhost: "ghosted by 14 companies and one (1) person you actually liked.",
  counterA: "applications: ",
  counterB: " \u00B7 responses: 0 \u00B7 dignity: offline",
} as const;
