// FEATURES copy. ASCII source only (non-ASCII as unicode escapes).
export const features = {
  h2: "what it actually does",
  lede: "(in between the breakdowns, real software happened)",
  c1t: "24 boards, one search",
  c1p: "LinkedIn direct; the walled boards (Indeed, Glassdoor, StepStone, Xing, Workday) via aggregator API \u2014 no new Workday account. Then Greenhouse, Lever, Ashby, and the whole DACH lineup \u2014 15 more places to be rejected, but faster.",
  c2t: "AI cover letters & r\u00e9sum\u00e9s",
  c2p: "Writes it for you. 12 templates \u2014 7 ATS-Safe tier (Classic, Swiss Minimal, Academic, Meridian, Throughline, Cadence, Regent) and 5 Design tier (Atelier, Portrait, Lebenslauf, Aria, Saffron), four with a headshot \u2014 rendered by a pure-Rust Typst engine to DOCX, PDF & TXT. The AI is more passionate about this role than you could ever convincingly fake.",
  c3t: "ATS scoring",
  c3p: "Your r\u00e9sum\u00e9 was reviewed by a piece of regex that has never felt joy. Now you score back.",
  c4t: "Semantic matching",
  c4p: "Hybrid vector search. Understands your r\u00e9sum\u00e9 better than your mother, who still thinks you \"do computers.\"",
  c5t: "Autopilot",
  c5p: "Pick a board and a schedule, walk away. At 9am it scrapes, ranks the matches, pings you, and pre-writes each tailored application. The submit button it leaves to you \u2014 some dignity must remain.",
  c6t: "Local, cloud, or CLI agents",
  c6p: "Run it free and offline with Ollama, drop in your own OpenAI/Anthropic/Gemini key, or route it through a CLI agent you already pay for \u2014 Claude Code, Codex, or Gemini CLI, no key needed. Your coding-agent subscription can finally do something about the unemployment.",
  c7t: "Company research, on tap",
  c7p: "Before it writes the letter, it quietly looks the company up \u2014 provider-native web search folded right into the prompt \u2014 so you don't have to fake admiring their \"mission.\" Opt-in. The robot does the admiring.",
  c8t: "Import anything (even a photo)",
  c8p: "Feed it your old r\u00e9sum\u00e9 as a PDF, DOCX, or a cursed phone photo \u2014 Tesseract OCRs it, the app re-parses it, and politely says nothing about the typos.",
  c9t: "11 languages (well, almost)",
  c9pA: "It ",
  c9pI: "writes",
  c9pB: " your r\u00e9sum\u00e9 in 11 \u2014 en, de, fr, es, it, tr, pt, ru, zh, ja, ko. The app's own interface speaks two for now, English and German; the other nine are \"coming soon,\" same as my big break. Cosmopolitan failure, localized.",
  c10t: "Privacy-first",
  c10p: "OS keychain, local SQLite, zero telemetry. No one is watching you spiral. For once.",
  c11t: "Browser extension (save jobs one-click)",
  c11pA: "While browsing any job board, one click imports that posting straight into your desktop app \u2014 no parsing, no copy-paste. The extension does the grabbing so your dignity doesn't have to. ",
  c11ChromeHref: "https://chromewebstore.google.com/detail/ai-job-hunter-%E2%80%94-job-impor/oaoekkgkhmgdfnpmfkpphgiikliaicll",
  c11Chrome: "Chrome",
  c11Sep: " \u00b7 ",
  c11FirefoxHref: "https://addons.mozilla.org/en-US/firefox/addon/ai-job-hunter-job-importer/",
  c11Firefox: "Firefox",
  c11pEnd: ".",
} as const;
