// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AgentRunRequest {
    pub resume_id: String,
    pub job_id: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct AgentConfirmRequest {
    pub job_id: String,
    pub call_id: String,
    pub decision: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub edited_args: Option<serde_json::Value>,
}
