// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

/// Every `AgentRunRequest.kind` the wire accepted. The FIRST entry is the
/// serde default (`prep_application`). The Rust-side registry this used to
/// pin (`agent::flows::FLOWS`) was deleted along with the rest of `agent/`
/// (PR-5 step 2); kept only because the renderer (PR-5 step 3) still
/// imports it via `@ajh/shared`.
pub const AGENT_FLOW_KINDS: &[&str] = &["prep_application", "improve_resume"];
