// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

/// Every `AgentRunRequest.kind` the wire accepts. The FIRST entry is the
/// serde default (`prep_application`), and `agent::flows::FLOWS` must carry
/// exactly one flow per token — pinned by
/// `agent::flows::tests::the_registry_covers_the_whole_wire_vocabulary`.
pub const AGENT_FLOW_KINDS: &[&str] = &["prep_application", "improve_resume"];
