// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/agent-caps.ts
#![allow(dead_code)]

/// Longest résumé text, in CHARACTERS, that may cross into an agent run:
/// the seed fence's clamp, the longest generation the `improve_resume` flow
/// can read, and the renderer threshold that disables the entry point. See
/// `AGENT_RESUME_TEXT_CAP` in packages/shared/src/agent-caps.ts for why the
/// three have to be one number.
pub const AGENT_RESUME_TEXT_CAP: usize = 8000;
