// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

pub const AI_GENERATE_INTENTS: &[&str] = &["deterministic", "prose", "prose_grounded", "default"];
