// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/ai-timeouts.ts
#![allow(dead_code)]

pub const STREAM_BASELINE_SECS: u64 = 300;

/// Ascending tier order — see the source-of-truth doc comment for why that
/// matters (`max` is the TOP tier, not `xhigh`). Any tier not listed here
/// (including `None`) gets an implicit 1.0 multiplier.
pub const EFFORT_TIMEOUT_MULTIPLIER: &[(&str, f64)] =
    &[("medium", 1.5), ("high", 2.0), ("xhigh", 2.5), ("max", 3.0)];

/// The EFFORT-INVARIANT half of one quality-depth run's deadline: every call
/// whose per-call bound is FLAT — the three JSON stages (each allowed one
/// re-ask), the repair fan-out (`max_repair_attempts` rounds ×
/// `MAX_SECTIONS_PER_ROUND` sections), and `humanize`'s up to 2
/// flagged-document calls, all bounded by `timeouts::OLLAMA_COMPLETION`.
/// See `qualityRunDeadlineSecs` in packages/shared/src/ai-timeouts.ts for
/// the full derivation.
pub const QUALITY_RUN_FIXED_SECS: u64 = 4800;

/// Effort-SCALED whole-document passes one quality run may make: two — the
/// draft, and the cover letter when `includeCoverLetter` is set. The repair
/// rounds and `humanize` are flat-bounded and live in
/// `QUALITY_RUN_FIXED_SECS` instead.
pub const QUALITY_RUN_GENERATION_PASSES: u64 = 2;
