// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

#[rustfmt::skip]
pub const BOARD_IDS: &[&str] = &[
    "linkedin",
    "arbeitsagentur",
    "berlinstartupjobs",
    "germantechjobs",
    "greenhouse",
    "lever",
    "ashby",
    "smartrecruiters",
    "recruitee",
    "personio",
    "pinpoint",
    "rippling",
    "breezy",
    "bamboohr",
    "workable",
    "comeet",
    "aggregator",
    "remoteok",
    "remotive",
    "arbeitnow",
    "jobicy",
    "themuse",
    "wwr",
    "ycombinator",
];
