// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/ai-context-window.ts
#![allow(dead_code)]

/// The smallest `num_ctx` worth sending: below this a window cannot hold a
/// system prompt plus any useful input, so the call is guaranteed to
/// truncate. Generated so the renderer slider and this validator cannot
/// disagree — see the source-of-truth module for the full rationale.
pub const MIN_CONTEXT_WINDOW: u32 = 512;

/// The largest: past this the request stops being a size and becomes an
/// out-of-memory kill of the user's machine, because Ollama allocates
/// `num_ctx` up front.
pub const MAX_CONTEXT_WINDOW: u32 = 131072;

/// What a PICKER starts at when the user has set nothing. The backend never
/// substitutes this: an absent window means the provider’s own default.
pub const DEFAULT_CONTEXT_WINDOW: u32 = 8192;
