// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

pub const DATE_FILTER_OPTIONS: &[&str] =
    &["15m", "30m", "1h", "2h", "4h", "8h", "24h", "week", "month"];
