// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct DedupMarkNotDuplicateRequest {
    pub member_key: String,
    pub other_keys: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub autopilot_id: Option<String>,
}
