// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct DiscoverySearchRequest {
    pub query: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ats_kind: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct DiscoveryStarRequest {
    pub ats_kind: String,
    pub slug: String,
    pub starred: bool,
}
