// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/events/index.ts
#![allow(dead_code)]

pub const AGENT_STEP: &str = "agent:step";
pub const AI_STREAM: &str = "ai:stream";
pub const JOBS_EVENT: &str = "jobs:event";
pub const APPLICATIONS_CHANGED: &str = "applications:changed";
pub const NOTIFICATIONS_CHANGED: &str = "notifications:changed";
pub const NOTIFICATIONS_OPEN: &str = "notifications:open";
pub const NOTIFICATIONS_TOAST: &str = "notifications:toast";
pub const UPDATER_STATUS: &str = "updater:status";
pub const MENU_NAVIGATE: &str = "menu:navigate";
pub const MENU_ACTION: &str = "menu:action";
pub const AUTOPILOT_FOCUS: &str = "autopilot:focus";
pub const AUTOPILOT_STEP: &str = "autopilot:step";
pub const PIPELINE_STAGE: &str = "pipeline:stage";
pub const SCRAPE_PROGRESS: &str = "scrape:progress";
pub const SCRAPE_ITEM: &str = "scrape:item";
pub const BOARDS_LOGIN_STATUS: &str = "boards:login-status";
pub const SYSTEM_ACCENT_CHANGED: &str = "system:accentChanged";
pub const EXTENSION_BRIDGE_CHANGED: &str = "extensionBridge:changed";

/// Closed phase vocabulary for a `pipeline:stage` event, in lifecycle order.
/// Source of truth: `PIPELINE_STAGE_PHASES` in
/// packages/shared/src/events/pipeline.ts.
pub const PIPELINE_STAGE_PHASES: &[&str] = &["start", "finish", "error"];

/// Longest a `pipeline:stage` event's `sectionKey` may be, in UTF-16 code
/// units (the unit the TS guard counts). Every LEGAL key is ASCII, so bytes,
/// chars and UTF-16 units agree for anything that could pass the grammar; a
/// byte-length check on a hostile value is only ever STRICTER, and such a
/// value fails the grammar regardless.
///
/// NORMATIVE: an over-length `sectionKey` must be REJECTED, never truncated —
/// a truncated key names a different section.
pub const SECTION_KEY_MAX_LENGTH: usize = 24;

/// The `sectionKey` values that carry no index — the fixed half of the closed
/// grammar (`summary` | `skills` | `experience:<u8>` | `projects` |
/// `education`). Source of truth: `PIPELINE_SECTION_KEYS_FIXED` in
/// packages/shared/src/events/pipeline.ts.
pub const PIPELINE_SECTION_KEYS_FIXED: &[&str] = &["summary", "skills", "projects", "education"];

/// Prefix of the indexed half: `experience:` followed by a decimal u8 with no
/// leading zeros. The index grammar itself is not codegen (a TS regex is not a
/// Rust one) — the Phase-3 emitter parses the remainder as a `u8`, which is the
/// same closed set.
pub const PIPELINE_SECTION_EXPERIENCE_PREFIX: &str = "experience:";
