// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

/// Historic `pipeline_runs.depth`/`QualityReport.pipeline` values — `fast`
/// is the renderer's own deterministic pass; `quality` is the only staged
/// depth a run may still request; `max` was removed.
pub const GENERATION_DEPTHS: &[&str] = &["fast", "quality", "max"];
