// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

/// Historic `pipeline_runs.depth`/`QualityReport.pipeline` values — closed
/// for READING, not for a request field. The wire request carries no
/// `depth` field; every new run persists the fixed value `quality`. `fast`
/// (the renderer's own deterministic pass) and `max` (a removed staged
/// depth) remain in this constant only so a historic row still round-trips.
pub const GENERATION_DEPTHS: &[&str] = &["fast", "quality", "max"];
