// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

/// Ascending depth order: `fast` is the untouched single-shot TS path,
/// `quality` and `max` are the staged Rust pipeline.
pub const GENERATION_DEPTHS: &[&str] = &["fast", "quality", "max"];
