// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct HelpSearchRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
    pub query: String,
    pub entries: Vec<HelpSearchRequestEntry>,
    #[serde(default = "default_help_search_request_limit")]
    pub limit: u32,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct HelpSearchRequestEntry {
    pub id: String,
    pub title: String,
    pub body: String,
}

fn default_help_search_request_limit() -> u32 {
    3
}
