// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts
#![allow(dead_code)]

/// `coverage` High cut — the embedding-free keyword-coverage kernel's
/// qualification bar. ponytail: heuristic starting values, not calibrated.
pub const MATCH_TIER_COVERAGE_HIGH: f64 = 55.0;

/// `coverage` Medium cut.
pub const MATCH_TIER_COVERAGE_MEDIUM: f64 = 30.0;

/// `combined` High cut — the semantic+ATS kernel's qualification bar.
pub const MATCH_TIER_COMBINED_HIGH: f64 = 75.0;

/// `combined` Medium cut.
pub const MATCH_TIER_COMBINED_MEDIUM: f64 = 50.0;
