// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/provider-slots.ts
#![allow(dead_code)]

pub const ADZUNA_APP_ID: &str = "adzuna-app-id";
pub const ADZUNA_APP_KEY: &str = "adzuna-app-key";
pub const JSEARCH_KEY: &str = "jsearch-key";
pub const APIFY_TOKEN: &str = "apify-token";
pub const COMEET_COMPANY_UID: &str = "comeet-company-uid";
pub const COMEET_API_TOKEN: &str = "comeet-api-token";
