// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.
// Source of truth: packages/shared/src/schemas/index.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct ResumePipelineRunRequest {
    pub resume_id: String,
    pub job_id: String,
    #[serde(default = "default_resume_pipeline_run_request_job_url")]
    pub job_url: String,
    #[serde(default = "default_resume_pipeline_run_request_depth")]
    pub depth: String,
    #[serde(default = "default_resume_pipeline_run_request_target_language")]
    pub target_language: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
    #[serde(default = "default_resume_pipeline_run_request_top_requirements")]
    pub top_requirements: Vec<String>,
    #[serde(default = "default_resume_pipeline_run_request_cover_letter_text")]
    pub cover_letter_text: String,
    #[serde(default = "default_resume_pipeline_run_request_include_cover_letter")]
    pub include_cover_letter: bool,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct ResumePipelineRegenerateSectionRequest {
    pub run_id: String,
    pub section_key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
#[allow(dead_code)]
pub struct ResumePipelineResolveFabricationRequest {
    pub run_id: String,
    pub issue_key: String,
    pub decision: String,
}

fn default_resume_pipeline_run_request_job_url() -> String {
    "".to_string()
}

fn default_resume_pipeline_run_request_depth() -> String {
    "quality".to_string()
}

fn default_resume_pipeline_run_request_target_language() -> String {
    "en".to_string()
}

fn default_resume_pipeline_run_request_top_requirements() -> Vec<String> {
    Vec::new()
}

fn default_resume_pipeline_run_request_cover_letter_text() -> String {
    "".to_string()
}

fn default_resume_pipeline_run_request_include_cover_letter() -> bool {
    false
}
