/**
 * Easy-Apply / Auto-Apply architecture.
 *
 * An `Applier` knows how to submit an application on a specific job board
 * given the user's profile data, a target posting URL, and an optional
 * AI-generated cover letter.
 *
 * Status: **scaffold only**. The LinkedIn applier below is a documented stub
 * that opens the apply flow, identifies the form, and stops short of clicking
 * submit. Building each board's apply path requires per-form selector maps
 * and live testing against the production UI — a careful, incremental effort.
 *
 * SECURITY:
 *  - Appliers run inside the same persistent Playwright context as the
 *    matching scraper, so the user's logged-in session is reused.
 *  - The user MUST explicitly opt into auto-submit per board. Until then,
 *    the applier stops at the final review screen.
 */
import type { BrowserController } from '../scraping/browser.js';

export interface ApplyContext {
  signal: AbortSignal;
  browser: BrowserController;
  /** Storage path for the board's persistent session. */
  storageStatePath: string;
  /** User credentials, if previously stored. */
  credentials?: { username: string; password: string } | null;
  /** Optional cover letter generated by the AI runtime. */
  coverLetter?: string;
  /** Optional resume PDF/DOCX to upload, if the board supports it. */
  resumePath?: string;
  onProgress?: (p: number, stage: string) => void;
  onStep?: (step: { stage: string; ok: boolean; note?: string }) => void;
  /**
   * When `false` (the default), the applier stops at the final review step
   * and returns the form's preview. When `true`, the applier actually clicks
   * submit. The user must explicitly opt in per run.
   */
  autoSubmit?: boolean;
}

export interface ApplyResult {
  ok: boolean;
  stage: string;
  submitted: boolean;
  url: string;
  note?: string;
}

export interface Applier {
  readonly boardId: string;
  readonly displayName: string;
  apply(postingUrl: string, ctx: ApplyContext): Promise<ApplyResult>;
}

export abstract class BaseApplier implements Applier {
  abstract readonly boardId: string;
  abstract readonly displayName: string;
  abstract apply(postingUrl: string, ctx: ApplyContext): Promise<ApplyResult>;
}
