// Regenerate the self-hosted web fonts in ../public/fonts/ (ADR-0018 origin
// invariant: no third-party font CDN on this origin). Fetches the Google Fonts
// css2 endpoint for the exact family/weight set the site uses, keeps only the
// latin + latin-ext subsets (the only ones this English site renders), downloads
// the woff2 files, and writes fonts.css with local, same-family @font-face rules
// (font-display: swap → zero visual change). Run: `pnpm --filter @ajh/landing gen:fonts`.
//
// Node stdlib only (Node 20+ global fetch). If the family/weight set changes,
// update FAMILIES below to match the pages, then re-run.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);

// Must cover every family/weight referenced by apps/landing/src/app/**/page.tsx.
const FAMILIES = [
  'Anton',
  'Caveat:wght@600;700',
  'Gloria+Hallelujah',
  'Patrick+Hand',
  'Space+Grotesk:wght@400;500;700',
  'Space+Mono:wght@400;700',
];

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

async function main() {
  const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;
  const cssRes = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!cssRes.ok) throw new Error(`css2 fetch failed: ${cssRes.status}`);
  const css = await cssRes.text();

  mkdirSync(OUT_DIR, { recursive: true });
  const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  const out = [];
  const downloads = [];
  let m;
  while ((m = blockRe.exec(css)) !== null) {
    const subset = m[1];
    if (!KEEP.has(subset)) continue;
    let block = m[2];
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1] ?? 'x';
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const src = /url\(([^)]+)\)/.exec(block)?.[1] ?? '';
    const name = `${slug(family)}-${weight}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;
    block = block.replace(/url\([^)]+\)/, `url('./${name}')`);
    out.push(`/* ${family} ${weight} ${style} · ${subset} */\n${block}`);
    downloads.push({ src, name });
  }

  for (const { src, name } of downloads) {
    const res = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`woff2 fetch failed ${res.status} for ${src}`);
    writeFileSync(join(OUT_DIR, name), Buffer.from(await res.arrayBuffer()));
  }

  const header =
    '/* Self-hosted web fonts — GENERATED by scripts/selfhost-fonts.mjs. Do not edit\n' +
    '   by hand. No third-party font CDN on this origin (ADR-0018 origin invariant).\n' +
    '   latin + latin-ext subsets only; same family names + font-display: swap. */\n\n';
  writeFileSync(join(OUT_DIR, 'fonts.css'), header + out.join('\n\n') + '\n');
  console.log(`gen:fonts — ${downloads.length} woff2 files + fonts.css (${out.length} @font-face)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
