import type { PipelineSectionKey, PipelineStageEvent } from '@ajh/shared';
import type { PipelineRunStatus } from '@ajh/shared/ipc';

import { createMachine } from '@/lib/machine';

/**
 * Staged résumé-generation (quality AND max depth) run state machine.
 *
 * One `resumePipeline.run` walks the Rust stage list for its depth — six at
 * quality (`analyze_job`, `match_evidence`, `strategy`, `draft`, `validate`,
 * `repair`) and eight at max (`draft` splits into `sections` + `assemble`, and
 * `llm_judge` runs LAST, after `repair`) — and this machine folds either list
 * into the same coarse states:
 *
 *   idle → queued → preparing → drafting → validating → repairing
 *                                        ↘ done | needsReview | cancelled | error
 *
 * The three JSON extraction stages collapse into one `preparing` state because
 * they are indistinguishable to a user (nothing streams, no document exists
 * yet); `index`/`total` off the event carries the real granularity into the
 * progress dots, and at max depth the per-section events carry the rest (see
 * `PipelineSectionState`). `stageToEvent` keys on the stage NAME, not on its
 * index, precisely because the two depths run different lists.
 *
 * **A max run therefore ends in `validating`, not `repairing`** — the judge is
 * a review pass over the finished document and reads as checking, and the
 * ordering is the backend's (`MAX_STAGES`), not this machine's opinion. Nothing
 * downstream depends on which busy state the last stage leaves behind: every
 * busy state is equally non-terminal, which is the invariant below.
 *
 * ## The one rule this machine exists to enforce
 *
 * **No stage event is terminal.** {@link stageToEvent} can never return
 * `COMPLETE`/`NEEDS_REVIEW`, and the last stage's `finish` leaves the machine in
 * a BUSY state (`repairing` at quality depth, `validating` at max). Two
 * independent reasons, both load-bearing:
 *
 * 1. The draft stage streams under the run's own umbrella `jobId`, so the shared
 *    stream machinery fires `job_complete` (and resolves `awaitAiStream`) the
 *    moment the draft's last delta lands — with validation and up to two repair
 *    rounds still to come. A renderer that treats that as "done" shows an
 *    unvalidated, unrepaired draft as final.
 * 2. A run stopped at a stage BOUNDARY (cancel, run deadline) emits no event at
 *    all for the stage it refused to start — `RunHooks::before` returns `Err`
 *    before its `start` emit — so "the last stage finished" is not even reliably
 *    observable.
 *
 * The authority on how a run ended is the run RECORD: feed
 * {@link statusToEvent}(detail.status) in and let it drive the terminal
 * transition. `stoppedReason` is explanatory only and may be absent on a
 * terminal run.
 */

/** The live progress of ONE stage, straight off the `pipeline:stage` payload. */
export interface PipelineStageProgress {
  stage: string;
  phase: PipelineStageEvent['phase'];
  /** 0-based position of this stage in the pipeline. */
  index: number;
  total: number;
  attempt: number;
  issueCount?: number;
  criticalCount?: number;
}

/**
 * Per-section lifecycle the plan's section timeline renders.
 *
 * The ladder belongs to MAX depth, where each section is generated by its own
 * call inside the `sections` stage. At quality depth the draft is one pass, so
 * no section ever enters it live.
 *
 * Which states are actually REACHABLE, and from where, is the thing to know
 * before reading a timeline built out of them — see {@link foldSectionStates}:
 * `generating`, `done`, `checking` and `clean` come off the live event stream;
 * `queued` is not observable at all; and `needsChanges`/`repaired` are verdicts
 * only the stored report can attribute to a section, after the run.
 */
export type PipelineSectionState =
  | 'queued'
  | 'generating'
  // Phase 4. The plan's ladder always had this rung — "written, not yet
  // checked" — and it is the ONE state a section spends real time in at max
  // depth: `sections` finishes each section long before `validate` starts.
  // The Phase 3 type skipped it because no event could reach it then; folding
  // `sections`/`finish` onto `checking` instead would claim a check that has
  // not run.
  | 'done'
  | 'checking'
  | 'needsChanges'
  | 'repaired'
  | 'clean';

/** Per-section verdicts for one run, keyed by the closed section grammar. */
export type PipelineSectionStates = Partial<Record<PipelineSectionKey, PipelineSectionState>>;

/**
 * Fold one `pipeline:stage` event into the per-section map the timeline renders.
 *
 * Pure, and returns `current` BY REFERENCE when nothing moved, so the caller's
 * `setState` bails out instead of re-rendering on every stage event of a run
 * that has no sections at all (quality depth).
 *
 * ## What the wire can and cannot prove
 *
 * Only two things put a section into a state, because only two are observable:
 *
 * - a `sections` event with a `sectionKey` — `start` ⇒ `generating`,
 *   `finish` ⇒ `done`. (The Rust `SectionProgress` emitter never sends `error`
 *   for a section: a section that produced nothing is a `finish`, because the
 *   run is degrading, not breaking.)
 * - the `validate` stage — its `start` moves everything already `done` to
 *   `checking`, and its `finish` may clear them.
 *
 * Everything else stays at its last honest value, deliberately:
 *
 * - **`queued` is never written.** The live event carries `index`/`total` of the
 *   STAGE, not of the section (`RunHooks::report_section` copies the stage's
 *   position), and the `{section, sections}` counts ride only in the PERSISTED
 *   artifact. The renderer therefore cannot know which sections are still
 *   coming — the roster depends on the strategy's company plan — and listing
 *   placeholder rows for them would invent sections a run may never generate. A
 *   section joins the map when its first event arrives, in generation order.
 * - **`validate` finishing with issues leaves sections at `checking`**, and
 *   `repaired` is never written at all. Neither the validate nor the repair
 *   artifact attributes anything to a section (`{issues, criticals, codes}` and
 *   `{rounds, reverted, …}` respectively), so per-section verdicts exist only
 *   AFTER the run, from the stored report — which is what `SectionVerdicts`
 *   renders. Writing `needsChanges`/`repaired` here would be a guess with a
 *   50/50 chance of naming the wrong section.
 * - `issueCount === 0` on `validate`'s finish is the one verdict the run-level
 *   counts DO prove per section: zero issues in the whole document is zero
 *   issues in each of its sections. An absent count proves nothing and is left
 *   alone.
 */
export function foldSectionStates(
  current: PipelineSectionStates,
  event: Pick<PipelineStageEvent, 'stage' | 'phase' | 'sectionKey' | 'issueCount'>
): PipelineSectionStates {
  if (event.stage === 'sections' && event.sectionKey) {
    const next: PipelineSectionState | null =
      event.phase === 'start' ? 'generating' : event.phase === 'finish' ? 'done' : null;
    if (!next || current[event.sectionKey] === next) return current;
    return { ...current, [event.sectionKey]: next };
  }

  if (event.stage === 'validate' && event.phase === 'start') {
    return remap(current, (state) => (state === 'done' ? 'checking' : state));
  }

  if (event.stage === 'validate' && event.phase === 'finish' && event.issueCount === 0) {
    return remap(current, (state) => (state === 'checking' ? 'clean' : state));
  }

  return current;
}

/** Apply `move` to every entry, returning the SAME object when nothing changed. */
function remap(
  states: PipelineSectionStates,
  move: (state: PipelineSectionState) => PipelineSectionState
): PipelineSectionStates {
  let changed = false;
  const next: PipelineSectionStates = {};
  for (const [key, state] of Object.entries(states) as [
    PipelineSectionKey,
    PipelineSectionState,
  ][]) {
    const moved = move(state);
    if (moved !== state) changed = true;
    next[key] = moved;
  }
  return changed ? next : states;
}

export type ResumePipelineState =
  | 'idle'
  | 'queued'
  | 'preparing'
  | 'drafting'
  | 'validating'
  | 'repairing'
  | 'done'
  | 'needsReview'
  | 'cancelled'
  | 'error';

export type ResumePipelineEvent =
  | 'START'
  | 'QUEUED'
  | 'PREPARE'
  | 'DRAFT'
  | 'VALIDATE'
  | 'REPAIR'
  | 'COMPLETE'
  | 'NEEDS_REVIEW'
  | 'CANCEL'
  | 'ERROR'
  | 'RESET';

/**
 * Transitions available from every non-terminal state. Stage events loop freely
 * among the busy states (a reconnect can arrive mid-run at any stage, and a
 * `get` replay walks them in order), and all four terminal events are reachable
 * from all of them — a run can fail, be cancelled, or come back `needsReview`
 * at any point.
 */
const BUSY_TRANSITIONS = {
  QUEUED: 'queued',
  PREPARE: 'preparing',
  DRAFT: 'drafting',
  VALIDATE: 'validating',
  REPAIR: 'repairing',
  COMPLETE: 'done',
  NEEDS_REVIEW: 'needsReview',
  CANCEL: 'cancelled',
  ERROR: 'error',
} as const;

/** Every terminal state restarts on `START` (a fresh run) as well as `RESET`. */
const TERMINAL_TRANSITIONS = { START: 'queued', RESET: 'idle' } as const;

export const resumePipelineMachine = createMachine<ResumePipelineState, ResumePipelineEvent>({
  transitions: {
    idle: { START: 'queued', RESET: 'idle' },
    queued: { ...BUSY_TRANSITIONS },
    preparing: { ...BUSY_TRANSITIONS },
    drafting: { ...BUSY_TRANSITIONS },
    validating: { ...BUSY_TRANSITIONS },
    repairing: { ...BUSY_TRANSITIONS },
    done: { ...TERMINAL_TRANSITIONS },
    // A run may leave `needsReview` for `done` once the user resolves the last
    // flagged bullet — the write commands return a fresh `PipelineRunDetail`
    // whose status drives that transition through `statusToEvent`.
    needsReview: { ...TERMINAL_TRANSITIONS, COMPLETE: 'done' },
    cancelled: { ...TERMINAL_TRANSITIONS },
    error: { ...TERMINAL_TRANSITIONS },
  },
  busyStates: ['queued', 'preparing', 'drafting', 'validating', 'repairing'],
  errorStates: ['error'],
});

/** The states in which the run is still doing work — nothing final to show. */
export const RESUME_PIPELINE_BUSY_STATES: readonly ResumePipelineState[] =
  resumePipelineMachine.busyStates ?? [];

/**
 * Stage names (Rust `Stage::name`) → the coarse state each one puts the run in.
 * A name this build doesn't know (a stage added after it shipped) maps to
 * nothing and leaves the machine where it is, which is honest: the progress
 * dots still advance off `index`/`total`.
 *
 * Both depths' lists live in one map because the names are unique across them:
 * quality's `draft` and max's `sections`/`assemble` are three different stages
 * that all mean "the document is being written", and `llm_judge` is max-only.
 * Keying on the name (rather than on a per-depth list) is also what keeps a
 * depth this build cannot enumerate from mapping to the WRONG state — it maps
 * to none.
 */
const STAGE_EVENTS: Record<string, ResumePipelineEvent> = {
  analyze_job: 'PREPARE',
  match_evidence: 'PREPARE',
  strategy: 'PREPARE',
  draft: 'DRAFT',
  // Max depth writes the document in two stages instead of one: `sections`
  // generates each section on its own and `assemble` renders them into the body
  // (pure, no provider call). Both are "writing" to a reader — the per-section
  // timeline is where the finer state lives.
  sections: 'DRAFT',
  assemble: 'DRAFT',
  validate: 'VALIDATE',
  repair: 'REPAIR',
  // The judge reads the FINISHED document (it runs after repair, last), so it
  // is a checking pass, not a repairing one. It cannot fail a run — its stage
  // records `{skipped}` on any error — so `VALIDATE` never strands a run: the
  // record's status is still what ends it.
  llm_judge: 'VALIDATE',
};

/**
 * Map one `pipeline:stage` event to a machine event.
 *
 * `error` is the only phase that can end a run here, and it does so because the
 * stage itself failed — not because the pipeline reached its end. **A `finish`
 * phase NEVER produces a terminal event**, not even for the last stage: see the
 * module doc. `null` means "stay where you are".
 */
export function stageToEvent(
  stage: string,
  phase: 'start' | 'finish' | 'error'
): ResumePipelineEvent | null {
  if (phase === 'error') return 'ERROR';
  if (phase === 'finish') return null;
  return STAGE_EVENTS[stage] ?? null;
}

/**
 * Map a run record's status to the machine event that ends (or doesn't end) the
 * run. This — not any stage event, not `jobs:event`, not `awaitAiStream` — is
 * the completion signal.
 *
 * `needsReview` is deliberately its own terminal state rather than a flavour of
 * `done`: the document is usable but carries findings awaiting a per-bullet
 * verdict, and a surface that renders it as clean is the failure the terminal
 * review exists to prevent.
 */
export function statusToEvent(status: PipelineRunStatus): ResumePipelineEvent | null {
  switch (status) {
    case 'running':
      return null;
    case 'completed':
      return 'COMPLETE';
    case 'needsReview':
      return 'NEEDS_REVIEW';
    case 'cancelled':
      return 'CANCEL';
    case 'failed':
      return 'ERROR';
  }
}
