// All shared UI primitives live in @ajh/ui.
// This barrel re-exports them so existing @/components/ui/* imports keep working.
export {
  ActionTile,
  Button,
  type ButtonProps,
  CardSkeleton,
  ConfirmModal,
  EmptyState,
  ErrorBoundary,
  ErrorState,
  GlassCard,
  type GlassCardProps,
  GlassOverlay,
  IconBadge,
  type IconBadgeProps,
  IconText,
  Input,
  type InputProps,
  MarkdownMessage,
  ModalShell,
  type ModalShellProps,
  OptionTile,
  RowSkeleton,
  SectionHeader,
  SectionLabel,
  SelectDropdown,
  SettingsSection,
  Skeleton,
  StreamingText,
  TextArea,
  type TextAreaProps,
  type ToastItem,
  ToastProvider,
  type ToastVariant,
  useToast,
} from '@ajh/ui';

// App-specific components (IPC/updater — cannot live in packages/ui)
export { UpdateBanner } from './UpdateBanner';
