// @generated by `pnpm gen:agent-catalogue` — DO NOT EDIT BY HAND.
// Source of truth: apps/desktop/src/tauri-client/namespaces/**/*.ts (argument shape)
//   + packages/shared/src/ipc/contracts/*.ts (description).
// Generator: packages/shared/scripts/gen-agent-catalogue.ts. Run `pnpm gen:agent-catalogue`.
// CI runs `pnpm gen:agent-catalogue:check` to catch drift.
//
// 162 commands catalogued across 3 shard file(s) (catalogue/shard_*.rs),
// 1 uncatalogued (see UNCATALOGUED below).
//
// Sharded rather than one big const array — this crate's own R8 hard LOC cap
// (docs/architecture-rules.md) has no exception for generated DATA, and rustfmt's own default
// `struct_lit_width` forces one field per line regardless of how short the whole literal is,
// so this file's size scales with the command count with no upper bound this generator
// controls. A `LazyLock<Vec<_>>` — never a `const` array-concat, which Rust cannot express
// across separately-compiled const items without an allocation — is transparent to every call
// site: `Deref<Target = Vec<CatalogueEntry>>` -> `Deref<Target = [CatalogueEntry]>` means
// `CATALOGUE.iter()`/`.find(...)` read exactly as they would against a plain slice.

use std::sync::LazyLock;

mod shard_1;
mod shard_2;
mod shard_3;

/// One declared argument of a [`CatalogueEntry`] — a top-level `--input`/`input` key exactly
/// as the tauri-client sends it, whether it is required, and — for a wrapper key typed as a
/// generated request struct or a plain contract interface — that type's own field names, so a
/// nested unknown field is catchable too.
///
/// `fields` is three-state: `None` — not a wrapper key at all (a scalar arg). `Some(&[])` —
/// a wrapper TYPE was identified but this generator could not resolve its field names (e.g.
/// a rest-destructured request object); dispatch-time validation treats this the same as
/// `None` (nothing to check a nested key against), but the `commands` MCP tool surfaces it
/// as `"fields": null`, distinct from omitting the key entirely, so a caller can tell
/// "known to take no nested fields" apart from "unknown nested shape". `Some([...])` —
/// resolved: that type's own field names.
#[derive(Clone, Copy)]
pub(crate) struct CatalogueArg {
    pub(crate) name: &'static str,
    pub(crate) required: bool,
    pub(crate) fields: Option<&'static [&'static str]>,
}

/// One dispatchable command's declared input contract (issues #1163, #1158, #1160).
#[derive(Clone, Copy)]
pub(crate) struct CatalogueEntry {
    pub(crate) command: &'static str,
    pub(crate) description: &'static str,
    pub(crate) args: &'static [CatalogueArg],
}

/// The full catalogue, assembled from every shard's own `ENTRIES` at first access — see this
/// file's own header comment for why a `LazyLock<Vec<_>>` and not a plain `const` slice.
pub(crate) static CATALOGUE: LazyLock<Vec<CatalogueEntry>> = LazyLock::new(|| {
    let mut entries = Vec::with_capacity(162);
    entries.extend_from_slice(shard_1::ENTRIES);
    entries.extend_from_slice(shard_2::ENTRIES);
    entries.extend_from_slice(shard_3::ENTRIES);
    entries
});

/// Commands with at least one `invoke()` call this generator could not parse with confidence
/// (a computed key, a spread, a non-literal command name, or a non-object second argument) —
/// listed rather than silently dropped. A command with NO `invoke()` call at all (zero
/// renderer references — see `policy.rs`'s own module doc) is absent from here too; the
/// coverage test pairs both arrays with a hand-written allowlist for exactly that case.
// Read only from `#[cfg(test)]` code today (the coverage test above) — a plain, non-test
// `cargo check --lib` sees no reader at all, so this stays legitimately unused OUTSIDE tests
// (never a silenced real finding — the RUST equivalent of `policy.rs`'s own module-level
// allow).
#[allow(dead_code)]
pub(crate) const UNCATALOGUED: &[&str] = &["dialog_open_files"];
