/**
 * IPC codegen — Zod schema → Rust request struct (proof of concept).
 *
 * The renderer, the IPC contract, the Rust command, and the TS client are
 * currently hand-synced (4 files per capability). This script makes the Zod
 * schemas in `src/schemas` the single source of truth for request shapes and
 * emits the matching Rust `Deserialize` structs, so the two can't drift.
 *
 * Run `pnpm gen:ipc` to regenerate, or `pnpm gen:ipc --check` to fail when the
 * committed output is stale (used in CI).
 *
 * Scope: this PoC covers the `scrape` namespace. Extend `MODULES` to add more.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

import { ScrapeBoardRequestSchema, ScrapeUrlRequestSchema } from '../src/schemas/index.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');

interface StructSpec {
  rustName: string;
  schema: z.ZodType;
}

interface ModuleSpec {
  /** Output file, relative to repo root. */
  outFile: string;
  structs: StructSpec[];
}

const MODULES: ModuleSpec[] = [
  {
    outFile: 'apps/tauri/src-tauri/src/ipc_contracts/scrape.rs',
    structs: [
      { rustName: 'ScrapeBoardRequest', schema: ScrapeBoardRequestSchema },
      { rustName: 'ScrapeUrlRequest', schema: ScrapeUrlRequestSchema },
    ],
  },
];

type JsonSchema = {
  type?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  enum?: unknown[];
  default?: unknown;
  minimum?: number;
};

function snakeCase(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

/** Map a JSON Schema property to a Rust type. */
function rustType(prop: JsonSchema): string {
  switch (prop.type) {
    case 'string':
      return 'String';
    case 'boolean':
      return 'bool';
    case 'number':
      return 'f64';
    case 'integer':
      return prop.minimum !== undefined && prop.minimum >= 0 ? 'u32' : 'i64';
    case 'array':
      return `Vec<${prop.items ? rustType(prop.items) : 'serde_json::Value'}>`;
    default:
      return 'serde_json::Value';
  }
}

/** Render a Rust literal for a JSON Schema default value. */
function rustDefault(prop: JsonSchema): string {
  if (prop.type === 'string') return `${JSON.stringify(prop.default)}.to_string()`;
  if (prop.type === 'boolean') return String(prop.default);
  return String(prop.default);
}

function genStruct(spec: StructSpec): { struct: string; helpers: string[] } {
  const schema = z.toJSONSchema(spec.schema) as JsonSchema;
  if (schema.type !== 'object' || !schema.properties) {
    throw new Error(`${spec.rustName}: only object schemas are supported`);
  }
  const required = new Set(schema.required ?? []);
  const helpers: string[] = [];
  const lines: string[] = [
    '#[derive(Debug, Deserialize)]',
    '#[serde(rename_all = "camelCase")]',
    `pub struct ${spec.rustName} {`,
  ];

  for (const [key, prop] of Object.entries(schema.properties)) {
    const field = snakeCase(key);
    const base = rustType(prop);
    const hasDefault = 'default' in prop;

    if (hasDefault) {
      const fn = `default_${snakeCase(spec.rustName)}_${field}`;
      helpers.push(`fn ${fn}() -> ${base} {\n    ${rustDefault(prop)}\n}`);
      lines.push(`    #[serde(default = "${fn}")]`);
      lines.push(`    pub ${field}: ${base},`);
    } else if (required.has(key)) {
      lines.push(`    pub ${field}: ${base},`);
    } else {
      lines.push(`    pub ${field}: Option<${base}>,`);
    }
  }

  lines.push('}');
  return { struct: lines.join('\n'), helpers };
}

function genModule(mod: ModuleSpec): string {
  const structs: string[] = [];
  const helpers: string[] = [];
  for (const spec of mod.structs) {
    const out = genStruct(spec);
    structs.push(out.struct);
    helpers.push(...out.helpers);
  }
  const body = [...structs, ...helpers].join('\n\n');
  return [
    '// @generated by `pnpm gen:ipc` — DO NOT EDIT BY HAND.',
    '// Source of truth: packages/shared/src/schemas/index.ts',
    '',
    'use serde::Deserialize;',
    '',
    body,
    '',
  ].join('\n');
}

const check = process.argv.includes('--check');
let stale = false;

for (const mod of MODULES) {
  const target = join(REPO_ROOT, mod.outFile);
  const next = genModule(mod);
  if (check) {
    let current: string;
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      current = '';
    }
    if (current !== next) {
      stale = true;
      console.error(`✗ stale: ${mod.outFile} — run \`pnpm gen:ipc\``);
    }
  } else {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, next);
    console.log(`✓ wrote ${mod.outFile}`);
  }
}

if (check && stale) process.exit(1);
if (check) console.log('✓ IPC codegen output is up to date');
